Repository SalesforceFoundation/NPSP, pull requests merged in 2019-10, with the labels that each got.

#4537 Orphaned Payment Allocation bug
  src/classes/RD_CascadeDeleteLookups_TDTM.cls
Labels: QE - Test

#4652 Initial Class structure for gift entry forms
  src/classes/FORM_Element.cls
  src/classes/FORM_Element.cls-meta.xml
  src/classes/FORM_Layout.cls
  src/classes/FORM_Layout.cls-meta.xml
  src/classes/FORM_Section.cls
  src/classes/FORM_Section.cls-meta.xml
  src/classes/FORM_Service.cls
  src/classes/FORM_Service.cls-meta.xml
  src/classes/FORM_ServiceGiftEntry.cls
  src/classes/FORM_ServiceGiftEntry.cls-meta.xml
  src/classes/FORM_ServiceGiftEntryTest.cls
  src/classes/FORM_ServiceGiftEntryTest.cls-meta.xml
  src/classes/FORM_Template.cls
  src/classes/FORM_Template.cls-meta.xml
  src/layouts/Form_Template__c-Form Template Layout.layout
  src/objects/Form_Template__c.object
  src/package.xml
Labels: Build Change Notes

#4573 RD2: Prevent legacy RD code execution when enhanced RDs are enabled
  src/classes/RD2_EnablementService.cls
  src/classes/RD2_EnablementService.cls-meta.xml
  src/classes/RD2_EnablementService_TEST.cls
  src/classes/RD2_EnablementService_TEST.cls-meta.xml
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/RD2_RecurringDonations_TDTM.cls-meta.xml
  src/classes/RD2_RecurringDonations_TEST.cls
  src/classes/RD2_RecurringDonations_TEST.cls-meta.xml
  src/classes/RD_RecurringDonations_BATCH.cls
  src/classes/RD_RecurringDonations_Opp_TDTM.cls
  src/classes/RD_RecurringDonations_TDTM.cls
  src/classes/RD_RecurringDonations_TEST2.cls
  src/classes/STG_PanelHealthCheck_TEST.cls
  src/classes/TDTM_DefaultConfig.cls
  src/classes/TEST_OpportunityBuilder.cls
  src/classes/TEST_OpportunityBuilder.cls-meta.xml
  src/classes/TEST_RecurringDonationBuilder.cls
  src/classes/TEST_SObjectGateway.cls
  src/objects/npe03__Recurring_Donations_Settings__c.object
  src/package.xml
Labels: Not-to-master, QE - Test

#4563 RD2: CCI Task to Deploy Unmanaged Metadata Field & Layout Changes
  cumulusci.yml
  tasks/__init__.py
  tasks/check_rd2_enablement.py
  unpackaged/config/rd2_post_config/layouts/npe03__Recurring_Donation__c-Enhanced Recurring Donations Layout.layout
  unpackaged/config/rd2_post_config/objectTranslations/npe03__Recurring_Donation__c-de.objectTranslation
  unpackaged/config/rd2_post_config/objectTranslations/npe03__Recurring_Donation__c-en_US.objectTranslation
  unpackaged/config/rd2_post_config/objectTranslations/npe03__Recurring_Donation__c-es.objectTranslation
  unpackaged/config/rd2_post_config/objectTranslations/npe03__Recurring_Donation__c-fr.objectTranslation
  unpackaged/config/rd2_post_config/objectTranslations/npe03__Recurring_Donation__c-iw.objectTranslation
  unpackaged/config/rd2_post_config/objectTranslations/npe03__Recurring_Donation__c-ja.objectTranslation
  unpackaged/config/rd2_post_config/objectTranslations/npe03__Recurring_Donation__c-nl_NL.objectTranslation
  unpackaged/config/rd2_post_config/objects/npe03__Recurring_Donation__c.object
  unpackaged/config/rd2_post_config/package.xml
  unpackaged/config/rd2_post_config/profiles/Admin.profile
  unpackaged/config/rd2_post_config/profiles/Standard.profile
Labels: Not-to-master

#4561 RD2: Auto-populate Recurring Donation Name
  src/classes/ACCT_CascadeDeleteLookups_TEST.cls
  src/classes/ALLO_Allocations_TEST.cls
  src/classes/ALLO_ManageAllocations_TEST.cls
  src/classes/CDL_CascadeDeleteLookups_TEST.cls
  src/classes/CON_DeleteContactOverride_TEST.cls
  src/classes/CRLP_RecalculateBTN_TEST.cls
  src/classes/CRLP_RollupRecurringDonation_TEST.cls
  src/classes/RD2_Donor.cls
  src/classes/RD2_Donor.cls-meta.xml
  src/classes/RD2_Donor_TEST.cls
  src/classes/RD2_Donor_TEST.cls-meta.xml
  src/classes/RD2_EnablementService.cls
  src/classes/RD2_EnablementService.cls-meta.xml
  src/classes/RD2_EnablementService_TEST.cls
  src/classes/RD2_EnablementService_TEST.cls-meta.xml
  src/classes/RD2_NamingService.cls
  src/classes/RD2_NamingService.cls-meta.xml
  src/classes/RD2_NamingService_TEST.cls
  src/classes/RD2_NamingService_TEST.cls-meta.xml
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/RD2_RecurringDonations_TDTM.cls-meta.xml
  src/classes/RD2_RecurringDonations_TEST.cls
  src/classes/RD2_RecurringDonations_TEST.cls-meta.xml
  src/classes/RD_BulkTests_TEST.cls
  src/classes/RD_CascadeDeleteLookups_TEST.cls
  src/classes/RD_RecurringDonations_BATCH.cls
  src/classes/RD_RecurringDonations_Opp_TDTM.cls
  src/classes/RD_RecurringDonations_TDTM.cls
  src/classes/RD_RecurringDonations_TEST.cls
  src/classes/RD_RecurringDonations_TEST2.cls
  src/classes/STG_InstallScript_TEST.cls
  src/classes/STG_PanelHealthCheck_TEST.cls
  src/classes/TDTM_DMLgt200_TEST.cls
  src/classes/TDTM_DefaultConfig.cls
  src/classes/TEST_OpportunityBuilder.cls
  src/classes/TEST_OpportunityBuilder.cls-meta.xml
  src/classes/TEST_RecurringDonationBuilder.cls
  src/classes/TEST_RecurringDonationBuilder.cls-meta.xml
  src/classes/TEST_SObjectGateway.cls
  src/classes/TEST_SObjectGateway.cls-meta.xml
  src/classes/UTIL_Currency.cls
  src/classes/UTIL_CustomSettingsFacade.cls
  src/classes/UTIL_OrgTelemetry_Batch_TEST.cls
  src/classes/UTIL_OrgTelemetry_TEST.cls
  src/labels/CustomLabels.labels
  src/objects/npe03__Recurring_Donations_Settings__c.object
  src/package.xml
Labels: Not-to-master

#4667 create dev_multicurrency org config
  cumulusci.yml
  orgs/dev_multicurrency.json
Labels: Infrastructure

#4665 RD2: Create Recurring Donation Schedule SObject
  src/layouts/RecurringDonationSchedule__c-Recurring Schedule Layout.layout
  src/objectTranslations/RecurringDonationSchedule__c-de.objectTranslation
  src/objectTranslations/RecurringDonationSchedule__c-en_US.objectTranslation
  src/objectTranslations/RecurringDonationSchedule__c-es.objectTranslation
  src/objectTranslations/RecurringDonationSchedule__c-fr.objectTranslation
  src/objectTranslations/RecurringDonationSchedule__c-iw.objectTranslation
  src/objectTranslations/RecurringDonationSchedule__c-ja.objectTranslation
  src/objectTranslations/RecurringDonationSchedule__c-nl_NL.objectTranslation
  src/objects/RecurringDonationSchedule__c.object
  src/package.xml
Labels: Not-to-master

#4689 Update RD2 Helptext for the Installment Period field
  unpackaged/config/rd2_post_config/objects/npe03__Recurring_Donation__c.object
Labels: Not-to-master

#4653 Fix the error in opp naming when there is no mapped currency symbol
  src/classes/OPP_OpportunityNaming.cls
Labels: QE - Test

#4658 Support Override of PilotEnabled for Dev and Testing work
  cumulusci.yml
  src/classes/UTIL_CustomSettingsFacade.cls
  src/classes/UTIL_FeatureEnablement.cls
  src/classes/UTIL_FeatureEnablement_TEST.cls
  src/classes/UTIL_Namespace.cls
  src/objects/Error_Settings__c.object
  src/package.xml
Labels: QE - Test

#4508 Update Trial metadata to match Contacts & Organizations
  unpackaged/config/trial/workflows/Contact.workflow
Labels: Infrastructure

#4681 Update RD2_Deploy_Config task for Release Version of RD Package
  unpackaged/config/rd2_post_config/objectTranslations/npe03__Recurring_Donation__c-en_US.objectTranslation
  unpackaged/config/rd2_post_config/objects/npe03__Recurring_Donation__c.object
Labels: Not-to-master

#4716 Update Trialforce id
  orgs/trial.json
Labels: Infrastructure

#4720 RD2: Constants Class
  src/classes/RD2_Constants.cls
  src/classes/RD2_Constants.cls-meta.xml
  src/package.xml
Labels: Not-to-master

#4728 CCI Flow for RD2 testing
  cumulusci.yml
Labels: Not-to-master

#4429 Switching a payment to negative bug
  src/classes/ALLO_Allocations_TDTM.cls
Labels: QE - Test, WIP

#4687 RD2: Validate Recurring Donation donor fields
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/RD2_ValidationService.cls
  src/classes/RD2_ValidationService.cls-meta.xml
  src/classes/RD2_ValidationService_TEST.cls
  src/classes/RD2_ValidationService_TEST.cls-meta.xml
  src/classes/UTIL_UnitTestData_TEST.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master, QE - Test

#4695 Gift Entry: batch header tab updates
  src/classes/FORM_BatchHeaderField.cls
  src/classes/FORM_Element.cls
  src/classes/GE_TemplateBuilderCtrl.cls
  src/lwc/geTemplateBuilder/geTemplateBuilder.html
  src/lwc/geTemplateBuilder/geTemplateBuilder.js
  src/lwc/geTemplateBuilderBatchHeader/geTemplateBuilderBatchHeader.html
  src/lwc/geTemplateBuilderBatchHeader/geTemplateBuilderBatchHeader.js
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.html
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.js
  src/lwc/geTemplateBuilderFormLayout/geTemplateBuilderFormLayout.js
  src/lwc/geTemplateBuilderFormSection/geTemplateBuilderFormSection.js
  src/lwc/geTemplateBuilderGiftFields/geTemplateBuilderGiftFields.js
  src/lwc/geTemplateBuilderTemplateInfo/geTemplateBuilderTemplateInfo.js
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
Labels: WIP

#4738 RD2: Migrate Recurring Donation fields
  src/classes/RD2_Constants.cls
  src/classes/RD2_DataMigrationMapper.cls
  src/classes/RD2_DataMigration_BATCH.cls
  src/classes/RD2_DataMigration_TEST.cls
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/classes/TEST_RecurringDonationBuilder.cls
  src/classes/TEST_SObjectGateway.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master, QE - Test
