Repository SalesforceFoundation/NPSP, pull requests merged in 2019-07, with the labels that each got.

#4335 Add is crlp is enabled to callable api
  src/classes/CRLP_ApiService.cls
  src/classes/Callable_API.cls
  src/classes/Callable_API_TEST.cls
Labels: QE - Test

#4390 Update Trial Template
  orgs/trial.json
Labels: Infrastructure

#4332 Telemetry for opportunity payments
  src/classes/UTIL_OrgTelemetry_BATCH.cls
  src/classes/UTIL_OrgTelemetry_Batch_TEST.cls
  src/classes/UTIL_OrgTelemetry_SObject_BATCH.cls
  src/classes/UTIL_OrgTelemetry_SObject_BATCH_TEST.cls
  src/classes/UTIL_OrgTelemetry_SVC.cls
  src/classes/UTIL_OrgTelemetry_SVC_TEST.cls
  src/classes/UTIL_OrgTelemetry_SVC_TEST.cls-meta.xml
  src/classes/UTIL_OrgTelemetry_TEST.cls
  src/featureParameters/DataCount_ONETIME_Use.featureParameterInteger
  src/featureParameters/Data_CountOppsWithMultiplePayments.featureParameterInteger
  src/package.xml
Labels: QE - Test

#4369 Feature/bdi co field mapping ui view
  cumulusci.yml
  sfdx-project.json
  src/aura/BDI_ManageAdvancedMapping/BDI_ManageAdvancedMapping.cmp
  src/aura/BDI_ManageAdvancedMapping/BDI_ManageAdvancedMapping.cmp-meta.xml
  src/aura/BDI_ManageAdvancedMapping/BDI_ManageAdvancedMapping.css
  src/aura/BDI_ManageAdvancedMapping/BDI_ManageAdvancedMappingController.js
  src/aura/BDI_ManageAdvancedMappingContainer/BDI_ManageAdvancedMappingContainer.app
  src/aura/BDI_ManageAdvancedMappingContainer/BDI_ManageAdvancedMappingContainer.app-meta.xml
  src/classes/BDI_FieldMappingCustomMetadata.cls
  src/classes/BDI_ManageAdvancedMappingCtrl.cls
  src/classes/BDI_ManageAdvancedMappingCtrl.cls-meta.xml
  src/classes/STG_PanelDataImportAdvancedMapping_CTRL.cls
  src/labels/CustomLabels.labels
  src/layouts/Data_Import_Field_Mapping__mdt-Data Import Field Mapping Layout.layout
  src/lwc/.eslintrc.json
  src/lwc/bdiFieldMappingModal/bdiFieldMappingModal.css
  src/lwc/bdiFieldMappingModal/bdiFieldMappingModal.html
  src/lwc/bdiFieldMappingModal/bdiFieldMappingModal.js
  src/lwc/bdiFieldMappingModal/bdiFieldMappingModal.js-meta.xml
  src/lwc/bdiFieldMappings/bdiFieldMappings.css
  src/lwc/bdiFieldMappings/bdiFieldMappings.html
  src/lwc/bdiFieldMappings/bdiFieldMappings.js
  src/lwc/bdiFieldMappings/bdiFieldMappings.js-meta.xml
  src/lwc/bdiObjectMappings/bdiObjectMappings.html
  src/lwc/bdiObjectMappings/bdiObjectMappings.js
  src/lwc/bdiObjectMappings/bdiObjectMappings.js-meta.xml
  src/lwc/jsconfig.json
  src/lwc/pubsubNoPageRef/pubsubNoPageRef.html
  src/lwc/pubsubNoPageRef/pubsubNoPageRef.js
  src/lwc/pubsubNoPageRef/pubsubNoPageRef.js-meta.xml
  src/lwc/utilPlatformEventListener/utilPlatformEventListener.html
  src/lwc/utilPlatformEventListener/utilPlatformEventListener.js
  src/lwc/utilPlatformEventListener/utilPlatformEventListener.js-meta.xml
  src/lwc/utilSearchableCombobox/utilSearchableCombobox.css
  src/lwc/utilSearchableCombobox/utilSearchableCombobox.html
  src/lwc/utilSearchableCombobox/utilSearchableCombobox.js
  src/lwc/utilSearchableCombobox/utilSearchableCombobox.js-meta.xml
  src/lwc/utilStencil/utilStencil.html
  src/lwc/utilStencil/utilStencil.js
  src/lwc/utilStencil/utilStencil.js-meta.xml
  src/objectTranslations/DeploymentEvent__e-en_US.objectTranslation
  src/objects/DeploymentEvent__e.object
  src/package.xml
  src/pages/BDI_ManageAdvancedMapping.page
  src/pages/BDI_ManageAdvancedMapping.page-meta.xml
  src/pages/STG_PanelDataImportAdvancedMapping.page
  src/tabs/Address__c.tab
  src/tabs/Batch_Data_Entry.tab
  src/tabs/Batch_Gift_Entry.tab
  src/tabs/Contact_Merge.tab
  src/tabs/DataImportBatch__c.tab
  src/tabs/DataImport__c.tab
  src/tabs/Engagement_Plan_Template__c.tab
  src/tabs/General_Accounting_Unit__c.tab
  src/tabs/Level__c.tab
  src/tabs/NPSP_Resources.tab
  src/tabs/NPSP_Settings.tab
  src/tabs/npe01__OppPayment__c.tab
  src/tabs/npe4__Relationship__c.tab
  src/tabs/npe5__Affiliation__c.tab
Labels: Not-to-master

#4372 TDTM Mutable
  src/classes/TDTM_Runnable.cls
  src/classes/TDTM_RunnableMutable.cls
  src/classes/TDTM_RunnableMutable.cls-meta.xml
  src/classes/TDTM_RunnableMutableMock_TEST.cls
  src/classes/TDTM_RunnableMutableMock_TEST.cls-meta.xml
  src/classes/TDTM_RunnableMutable_TEST.cls
  src/classes/TDTM_RunnableMutable_TEST.cls-meta.xml
  src/classes/TDTM_TriggerHandler.cls
  src/package.xml
Labels: Community

#4407 Feature/bdi co field mapping ui update wrapper class
  src/classes/BDI_ManageAdvancedMappingCtrl.cls
  src/lwc/bdiFieldMappingModal/bdiFieldMappingModal.js
  src/lwc/bdiFieldMappings/bdiFieldMappings.js
  src/lwc/jsconfig.json
Labels: Not-to-master

#4412 Feature/bdi co fix namespace bug for data import field mappings
  src/classes/BDI_ManageAdvancedMappingCtrl.cls
Labels: Not-to-master

#4419 Feature/bdi co qa org flow metadata fix
  unpackaged/config/qa/customMetadata/Data_Import_Field_Mapping_Set.Migrated_Custom_Field_Mapping_Set.md
  unpackaged/config/qa/customMetadata/Data_Import_Object_Mapping.CustomObject1_7b96c6e1b.md
  unpackaged/config/qa/customMetadata/Data_Import_Object_Mapping.CustomObject3_f3f9b20ad.md
  unpackaged/config/qa/customMetadata/Data_Import_Object_Mapping.WorkOrder_f516282fb.md
  unpackaged/config/qa/customMetadata/Data_Import_Object_Mapping_Set.Migrated_Custom_Object_Mapping_Set.md
  unpackaged/config/qa/package.xml
Labels: Not-to-master

#4420 Feature/bdi co fix modal overlay and responsiveness
  src/aura/BDI_ManageAdvancedMapping/BDI_ManageAdvancedMapping.css
  src/lwc/bdiFieldMappingModal/bdiFieldMappingModal.css
  src/lwc/bdiFieldMappingModal/bdiFieldMappingModal.html
  src/lwc/bdiObjectMappingModal/bdiObjectMappingModal.css
  src/lwc/bdiObjectMappingModal/bdiObjectMappingModal.html
  src/lwc/utilSearchableCombobox/utilSearchableCombobox.css
Labels: Not-to-master

#4401 Feature/bdi co field mapping ui sortable datatable
  src/lwc/bdiFieldMappings/bdiFieldMappings.html
  src/lwc/bdiFieldMappings/bdiFieldMappings.js
Labels: Not-to-master

#4400 Feature/bdi co add field-side help text check for migration util
  src/classes/BDI_MigrationMappingUtility.cls
  src/classes/BDI_MigrationMappingUtilityTest.cls
  src/classes/STG_PanelDataImportAdvancedMapping_CTRL.cls
Labels: Not-to-master

#4282 BGE: Remove "Update this Opportunity" link in BGE Donation Selector component when Opportunity has existing Payments
  src/aura/BGE_DonationSelector/BGE_DonationSelector.cmp
  src/aura/BGE_EntryForm/BGE_EntryFormController.js
  src/aura/BGE_EntryForm/BGE_EntryFormHelper.js
  src/classes/BGE_DataImportBatchEntry_CTRL.cls
  src/classes/BGE_DataImportBatchEntry_CTRL_TEST.cls
Labels: WIP

#4436 Added Object Translation files for Opportunity Stage to State Custom Metadata
  src/objectTranslations/Opportunity_Stage_To_State_Mapping__mdt-de.objectTranslation
  src/objectTranslations/Opportunity_Stage_To_State_Mapping__mdt-en_US.objectTranslation
  src/objectTranslations/Opportunity_Stage_To_State_Mapping__mdt-es.objectTranslation
  src/objectTranslations/Opportunity_Stage_To_State_Mapping__mdt-fr.objectTranslation
  src/objectTranslations/Opportunity_Stage_To_State_Mapping__mdt-iw.objectTranslation
  src/objectTranslations/Opportunity_Stage_To_State_Mapping__mdt-ja.objectTranslation
  src/objectTranslations/Opportunity_Stage_To_State_Mapping__mdt-nl_NL.objectTranslation
  src/package.xml
Labels: WIP

#4442 Feature/bdi co add field to dataimport object for qa org config
  unpackaged/config/qa/objects/___NAMESPACE___DataImport__c.object
  unpackaged/config/qa/package.xml
Labels: Not-to-master

#4443 Feature/bdi co update migration utility object mapping query
  src/classes/BDI_MigrationMappingHelper.cls
Labels: Not-to-master

#4430 Feature/bdi co add unit tests
  src/classes/BDI_ManageAdvancedMappingCtrl.cls
  src/classes/BDI_ManageAdvancedMappingCtrlTest.cls
  src/classes/BDI_ManageAdvancedMappingCtrlTest.cls-meta.xml
  src/package.xml
Labels: Not-to-master

#4444 Feature/bdi co update valid datatype mappings
  src/lwc/bdiFieldMappingModal/bdiFieldMappingModal.js
Labels: Not-to-master

#4428 feature/bdi co update migration page style
  src/pages/STG_PanelDataImportAdvancedMapping.page
Labels: Not-to-master

#4342 Duplicate GAU Allocation Bug
  src/classes/ALLO_Allocations_TDTM.cls
  src/classes/ALLO_Allocations_TEST.cls
  src/classes/ALLO_PaymentSync_SVC.cls
Labels: WIP

#4434 add inline help text to field mapping modal
  src/classes/STG_PanelDataImportAdvancedMapping_CTRL.cls
  src/classes/UTIL_HtmlOutput_CTRL.cls
  src/labels/CustomLabels.labels
  src/lwc/bdiFieldMappingModal/bdiFieldMappingModal.html
  src/lwc/bdiFieldMappingModal/bdiFieldMappingModal.js
  src/lwc/bdiFieldMappings/bdiFieldMappings.html
  src/lwc/bdiFieldMappings/bdiFieldMappings.js
  src/objects/DataImport__c.object
  src/objects/Data_Import_Field_Mapping__mdt.object
  src/package.xml
  src/pages/STG_PanelDataImportAdvancedMapping.page
Labels: Not-to-master

#4452 Feature/bdi co fix issues
  src/lwc/bdiFieldMappings/bdiFieldMappings.js
  src/lwc/bdiObjectMappings/bdiObjectMappings.js
  src/lwc/utilPlatformEventListener/utilPlatformEventListener.js
Labels: Not-to-master

#4456 Feature/bdi co fix deleted field mappings being validated
  src/classes/BDI_FieldMappingCustomMetadata.cls
Labels: Not-to-master

#4464 Feature/bdi co remove unused lightning app and vfp
  src/aura/BDI_ManageAdvancedMappingContainer/BDI_ManageAdvancedMappingContainer.app
  src/aura/BDI_ManageAdvancedMappingContainer/BDI_ManageAdvancedMappingContainer.app-meta.xml
  src/package.xml
  src/pages/BDI_ManageAdvancedMapping.page
  src/pages/BDI_ManageAdvancedMapping.page-meta.xml
Labels: Not-to-master
