Repository SalesforceFoundation/NPSP, pull requests merged in 2019-11, with the labels that each got.

#4751 RD2: Create Schedule records during data migration
  src/classes/RD2_DataMigrationMapper.cls
  src/classes/RD2_DataMigration_TEST.cls
Labels: Not-to-master

#4743 RD2: Disable the RD Next Payment Date Customizable Rollup during enablement
  src/classes/CRLP_DefaultConfigBuilder_SVC.cls
  src/classes/CRLP_RollupCMT.cls
  src/classes/RD2_EnablementDelegate_CTRL.cls
  src/classes/RD2_EnablementDelegate_TEST.cls
Labels: Not-to-master

#4748 HGE - Picklist Support
  .gitignore
  src/aura/geFormRendererPlaceholder/geFormRendererPlaceholder.css
  src/lwc/geFormField/geFormField.html
  src/lwc/geFormFieldPicklist/geFormFieldPicklist.html
  src/lwc/geFormFieldPicklist/geFormFieldPicklist.js
  src/lwc/geFormFieldPicklist/geFormFieldPicklist.js-meta.xml
  src/package.xml
Labels: Not-to-master

#4727 RD2: Create new Opportunities for specified Recurring Donations
  src/classes/RD2_OpportunityService.cls
  src/classes/RD2_OpportunityService.cls-meta.xml
  src/classes/RD2_OpportunityService_TEST.cls
  src/classes/RD2_OpportunityService_TEST.cls-meta.xml
  src/classes/UTIL_CustomSettingsFacade.cls
  src/package.xml
Labels: Not-to-master

#4725 Translation Fixes
  src/components/RP_GettingStarted.component
  src/components/RP_Youtube.component
  src/labels/CustomLabels.labels
Labels: Not-to-master

#4760 RD2: If DayOfMonth is null, set using NextPaymentDate or DateEstablished
  src/classes/RD2_DataMigrationMapper.cls
  src/classes/RD2_DataMigration_TEST.cls
  unpackaged/config/rd2_post_config/objects/npe03__Recurring_Donation__c.object
Labels: Not-to-master

#4750 RD2: Calculate Next Donation Date Service
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/RD2_RecurringDonations_TEST.cls
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
Labels: Not-to-master

#4752 RD2: Enable user to start and view data migration
  src/aura/RD2_EnablementDelegate/RD2_EnablementDelegate.cmp
  src/aura/RD2_EnablementDelegate/RD2_EnablementDelegateController.js
  src/aura/RD2_EnablementDelegate/RD2_EnablementDelegateHelper.js
  src/classes/RD2_DataMigration_BATCH.cls
  src/classes/RD2_EnablementDelegate_CTRL.cls
  src/classes/RD2_EnablementDelegate_TEST.cls
  src/classes/UTIL_BatchJobProgress_CTRL.cls
  src/classes/UTIL_BatchJobProgress_CTRL.cls-meta.xml
  src/classes/UTIL_BatchJobProgress_TEST.cls
  src/classes/UTIL_BatchJobProgress_TEST.cls-meta.xml
  src/classes/UTIL_BatchJobService.cls
  src/classes/UTIL_BatchJobService.cls-meta.xml
  src/classes/UTIL_BatchJobService_TEST.cls
  src/classes/UTIL_BatchJobService_TEST.cls-meta.xml
  src/classes/UTIL_CustomSettingsFacade.cls
  src/labels/CustomLabels.labels
  src/lwc/batchProgress/batchProgress.html
  src/lwc/batchProgress/batchProgress.js
  src/lwc/batchProgress/batchProgress.js-meta.xml
  src/lwc/jsconfig.json
  src/lwc/progressRing/progressRing.js
  src/objects/npe03__Recurring_Donations_Settings__c.object
  src/package.xml
Labels: Not-to-master

#4767 RD2: Fix Unit Test Failures
  src/classes/RD2_EnablementService_TEST.cls
  src/classes/RD2_OpportunityEvaluationService_TEST.cls
  src/classes/RD2_OpportunityService_TEST.cls
  src/classes/TEST_RecurringDonationBuilder.cls
Labels: Not-to-master

#4769 Update Trialforce Template Id
  orgs/trial.json
Labels: Infrastructure

#4764 [RD] Synchronize Schedule object based on RD info
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/RD2_RecurringDonations_TEST.cls
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/classes/TEST_SObjectGateway.cls
Labels: Not-to-master, QE - Test

#4779 RD2: Create one Schedule per RD during legacy to enhanced RD data migration
  src/classes/RD2_DataMigrationMapper.cls
  src/classes/RD2_DataMigration_BATCH.cls
  src/classes/RD2_DataMigration_TEST.cls
Labels: QE - Test

#4777 Feature/gift entry form save
  src/classes/BDI_ContactService.cls
  src/classes/FORM_Service.cls
  src/classes/FORM_ServiceGiftEntry.cls
  src/classes/FORM_ServiceGiftEntryTest.cls
  src/classes/GE_FormRendererService.cls
  src/classes/GE_FormRendererService_TEST.cls
  src/classes/GE_FormRendererService_TEST.cls-meta.xml
  src/classes/GE_TemplateBuilderCtrl.cls
  src/labels/CustomLabels.labels
  src/lwc/geFormField/geFormField.html
  src/lwc/geFormField/geFormField.js
  src/lwc/geFormFieldPicklist/geFormFieldPicklist.js
  src/lwc/geFormRenderer/geFormRenderer.css
  src/lwc/geFormRenderer/geFormRenderer.html
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geFormSection/geFormSection.js
  src/lwc/geFormService/geFormService.js
  src/package.xml
Labels: Not-to-master

#4791 RD2: Specialized Opportunity Naming when creating Installment Opportunities
  src/classes/RD2_OpportunityService.cls
  src/classes/RD2_OpportunityService_TEST.cls
  src/classes/TEST_RecurringDonationBuilder.cls
Labels: Not-to-master

#4830 Gift Entry: Patch issue with removal of form element property 'value'
  src/lwc/geFormField/geFormField.js
Labels: Not-to-master

#4813 Update trial template to 3.165
  orgs/trial.json
Labels: Infrastructure

#4787 refactoring org settings json
  orgs/beta.json
  orgs/beta_middlesuffix.json
  orgs/beta_multicurrency.json
  orgs/beta_personaccounts.json
  orgs/beta_platformencryption.json
  orgs/beta_prerelease.json
  orgs/beta_statecountry.json
  orgs/dev.json
  orgs/dev_multicurrency.json
  orgs/enterprise.json
  orgs/feature.json
  orgs/prerelease.json
  orgs/release.json
  orgs/trial.json
Labels: Infrastructure

#4832 Enable test retries
  cumulusci.yml
Labels: Infrastructure

#4802 RD2: Handle Installment Opportunities when an RD is closed
  src/classes/RD2_Constants.cls
  src/classes/RD2_DataMigration_TEST.cls
  src/classes/RD2_EnablementDelegate_TEST.cls
  src/classes/RD2_EnablementService_TEST.cls
  src/classes/RD2_NamingService_TEST.cls
  src/classes/RD2_OpportunityEvaluationService.cls
  src/classes/RD2_OpportunityEvaluationService_TEST.cls
  src/classes/RD2_OpportunityService.cls
  src/classes/RD2_OpportunityService_TEST.cls
  src/classes/RD2_QueueableService.cls
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/RD_RecurringDonations.cls
  src/classes/TEST_SObjectGateway.cls
  src/classes/UTIL_DMLService.cls
  src/classes/UTIL_DMLService_TEST.cls
Labels: Not-to-master

#4800 [RD] Fix Issues with StartDate When a Schedule is Modified
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/RD2_RecurringDonations_TEST.cls
  src/classes/RD2_ScheduleService.cls
Labels: Not-to-master, QE - Test

#4789 RD2: Nightly Batch Framework
  src/classes/RD2_EnablementDelegate_CTRL.cls
  src/classes/RD2_EnablementDelegate_TEST.cls
  src/classes/RD2_OpportunityEvaluationService.cls
  src/classes/RD2_OpportunityEvaluation_BATCH.cls
  src/classes/RD2_OpportunityEvaluation_BATCH.cls-meta.xml
  src/classes/RD2_OpportunityEvaluation_TEST.cls
  src/classes/RD2_OpportunityEvaluation_TEST.cls-meta.xml
  src/classes/RD_RecurringDonations_BATCH.cls
  src/classes/RD_RecurringDonations_TEST2.cls
  src/classes/STG_PanelCustomizableRollup_CTRL.cls
  src/classes/STG_PanelRDBatch_CTRL.cls
  src/classes/UTIL_BatchJobService.cls
  src/classes/UTIL_MasterSchedulableHelper.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master

#4790 RD2: Enablement page cleanup
  src/aura/RD2_EnablementDelegate/RD2_EnablementDelegate.cmp
  src/aura/RD2_EnablementDelegate/RD2_EnablementDelegateHelper.js
  src/labels/CustomLabels.labels
  src/lwc/batchProgress/batchProgress.html
  src/lwc/progressRing/progressRing.js
Labels: Not-to-master, QE - Test

#4786 [RD] Changes to the Recurring Donation Future Schedule should not create invalid overlapping schedules
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/objects/RecurringDonationSchedule__c.object
Labels: Not-to-master, QE - Test

#4805 Expose Payment Allocations batch logic for invocation via Callable API
  src/classes/ALLO_AllocationsUtil_TEST.cls
  src/classes/CallableApiParameters.cls
  src/classes/Callable_API.cls
  src/classes/Callable_API_TEST.cls
Labels: Not-to-master
