Repository SalesforceFoundation/NPSP, pull requests merged in 2019-12, with the labels that each got.

#4808 First pass at adding a Widget component to Gift Entry
  src/classes/GE_FormRendererService.cls
  src/classes/GE_FormRendererService_TEST.cls
  src/lwc/geFormSection/geFormSection.html
  src/lwc/geFormSection/geFormSection.js
  src/lwc/geFormService/geFormService.js
  src/lwc/geFormWidget/geFormField.js-meta.xml
  src/lwc/geFormWidget/geFormWidget.html
  src/lwc/geFormWidget/geFormWidget.js
  src/lwc/geFormWidgetAllocation/geFormWidgetAllocation.html
  src/lwc/geFormWidgetAllocation/geFormWidgetAllocation.js
  src/lwc/geFormWidgetAllocation/geFormWidgetAllocation.js-meta.xml
  src/lwc/geFormWidgetRow/geFormWidgetRow.html
  src/lwc/geFormWidgetRow/geFormWidgetRow.js
  src/lwc/geFormWidgetRow/geFormWidgetRow.js-meta.xml
  src/lwc/geTemplateBuilderService/geTemplateBuilderService.js
  src/package.xml
Labels: Not-to-master

#4834 RD2: Validate enhanced RD fields
  src/classes/RD2_Constants.cls
  src/classes/RD2_EnablementService_TEST.cls
  src/classes/RD2_RecurringDonations_TEST.cls
  src/classes/RD2_ValidationService.cls
  src/classes/RD2_ValidationService_TEST.cls
  src/classes/TEST_RecurringDonationBuilder.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master, QE - Test

#4831 RD2: Log data migration errors
  src/classes/CRLP_RollupAccSoftCredit_TEST.cls
  src/classes/CRLP_RollupAccount_TEST.cls
  src/classes/ERR_Handler.cls
  src/classes/ERR_Handler_TEST.cls
  src/classes/OPP_CurrencySync_TEST.cls
  src/classes/RD2_DataMigrationMapper.cls
  src/classes/RD2_DataMigration_BATCH.cls
  src/classes/RD2_DataMigration_TEST.cls
  src/classes/RD2_EnablementDelegate_TEST.cls
  src/classes/RD2_OpportunityService_TEST.cls
  src/classes/RD2_ValidationService_TEST.cls
  src/classes/TEST_SObjectGateway.cls
  src/classes/UTIL_BatchJobService.cls
  src/classes/UTIL_BatchJobService_TEST.cls
  src/classes/UTIL_UnitTestData_TEST.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master, QE - Test

#4850 RD2: Use configured Record Type when creating new RD Installment Opportunities
  src/classes/RD2_OpportunityService.cls
  src/classes/RD2_OpportunityService_TEST.cls
  src/classes/UTIL_CustomSettingsFacade.cls
  src/classes/UTIL_RecordTypes_TEST.cls
Labels: Not-to-master

#4855 RD2: Data migration - void open Opps
  src/classes/ERR_Handler.cls
  src/classes/RD2_DataMigrationMapper.cls
  src/classes/RD2_DataMigration_BATCH.cls
  src/classes/RD2_DataMigration_TEST.cls
  src/classes/RD2_OpportunityEvaluationService.cls
  src/classes/RD2_ValidationService_TEST.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master

#4745 NPSP Drop 3 LQA Fixes - cumulus
  src/translations/nl_NL.translation
Labels: Do Not Merge, Not-to-master

#4876 RD2: Display data migration errors
  src/aura/RD2_EnablementDelegate/RD2_EnablementDelegate.cmp
  src/aura/RD2_EnablementDelegate/RD2_EnablementDelegateController.js
  src/aura/RD2_EnablementDelegate/RD2_EnablementDelegateHelper.js
  src/classes/RD2_DataMigration_BATCH.cls
  src/classes/RD2_DataMigration_TEST.cls
  src/classes/RD2_EnablementDelegate_CTRL.cls
  src/classes/RD2_EnablementDelegate_TEST.cls
  src/classes/TEST_SObjectGateway.cls
  src/classes/UTIL_BatchJobProgress_CTRL.cls
  src/classes/UTIL_BatchJobProgress_TEST.cls
  src/classes/UTIL_BatchJobService.cls
  src/classes/UTIL_BatchJobService_TEST.cls
  src/labels/CustomLabels.labels
  src/lwc/batchProgress/batchProgress.html
  src/lwc/batchProgress/batchProgress.js
  src/lwc/jsconfig.json
  src/lwc/util/util.js
  src/lwc/util/util.js-meta.xml
  src/objects/npe03__Recurring_Donations_Settings__c.object
  src/package.xml
Labels: Not-to-master

#4856 RD2: Do not display legacy Recurring Donations settings after enablement
  src/aura/RD2_EnablementDelegate/RD2_EnablementDelegate.cmp
  src/aura/RD2_EnablementDelegate/RD2_EnablementDelegateHelper.js
  src/aura/RD2_EnhancementEnabledEvent/RD2_EnhancementEnabledEvent.evt
  src/aura/RD2_EnhancementEnabledEvent/RD2_EnhancementEnabledEvent.evt-meta.xml
  src/classes/RD2_EnablementDelegate_CTRL.cls
  src/classes/STG_Panel.cls
  src/classes/STG_PanelRD_CTRL.cls
  src/classes/STG_SettingsManager_CTRL.cls
  src/classes/STG_SettingsManager_TEST.cls
  src/labels/CustomLabels.labels
  src/package.xml
  src/pages/STG_PanelCustomizableRollup.page
  src/pages/STG_PanelRD.page
  src/pages/STG_PanelRD2Enablement.page
  src/pages/STG_PanelRDCustomFieldMapping.page
  src/pages/STG_PanelRDCustomInstallment.page
  src/pages/STG_SettingsManager.page
Labels: Not-to-master

#4874 Gift Entry: add custom labels
  src/aura/GE_TemplateBuilder/GE_TemplateBuilderController.js
  src/labels/CustomLabels.labels
  src/lwc/geLabelService/geLabelService.js
  src/lwc/geLabelService/geLabelService.js-meta.xml
  src/lwc/geTemplateBuilder/geTemplateBuilder.html
  src/lwc/geTemplateBuilder/geTemplateBuilder.js
  src/lwc/geTemplateBuilderBatchHeader/geTemplateBuilderBatchHeader.html
  src/lwc/geTemplateBuilderBatchHeader/geTemplateBuilderBatchHeader.js
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.html
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.js
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.css
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.html
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.js
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.js-meta.xml
  src/lwc/geTemplateBuilderFormSection/geTemplateBuilderFormSection.html
  src/lwc/geTemplateBuilderFormSection/geTemplateBuilderFormSection.js
  src/lwc/geTemplateBuilderSectionModalBody/geTemplateBuilderSectionModalBody.html
  src/lwc/geTemplateBuilderSectionModalBody/geTemplateBuilderSectionModalBody.js
  src/lwc/geTemplateBuilderTemplateInfo/geTemplateBuilderTemplateInfo.html
  src/lwc/geTemplateBuilderTemplateInfo/geTemplateBuilderTemplateInfo.js
  src/lwc/geTemplates/geTemplates.html
  src/lwc/geTemplates/geTemplates.js
  src/lwc/utilPageLevelMessage/utilPageLevelMessage.js
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
  src/package.xml
Labels: Not-to-master

#4895 Updated TSO id to NPSP 3.166
  orgs/trial.json
Labels: Infrastructure

#4901 Emergency Fix for Duplicate Field in CRLP Rollup Queries
  src/classes/CRLP_Query_SEL.cls
Labels: bug

#4892 Gift Entry: add DataImport__c.Donation_Donor__c field as a simulated Field Mapping
  src/classes/BDI_MappingServiceAdvanced.cls
  src/classes/BDI_MappingServiceAdvanced_TEST.cls
  src/classes/GE_FormRendererService.cls
  src/lwc/geFormFieldPicklist/geFormFieldPicklist.html
  src/lwc/geFormFieldPicklist/geFormFieldPicklist.js
  src/lwc/geTemplateBuilder/geTemplateBuilder.html
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.html
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.js
  src/lwc/geTemplateBuilderService/geTemplateBuilderService.js
Labels: Not-to-master

#4891 Gift Entry: add Object Mapping 'imported' fields as a simulated Field Mappings
  src/classes/BDI_MappingServiceAdvanced.cls
  src/classes/BDI_MappingServiceAdvanced_TEST.cls
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.js
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.js
Labels: Not-to-master

#4889 Cumulus -> NPSP
  ApexDocContent/homepage.htm
  ApexDocContent/projectheader.htm
  README.md
  cumulusci.yml
  src/classes/RP_Constants.cls
  src/classes/RP_GitHubTestMock.cls
Labels: Infrastructure
