Repository SalesforceFoundation/NPSP, pull requests merged in 2019-09, with the labels that each got.

#4529 Community Contribution: Remove duplicate component
  src/aura/dataProviderInterface/dataProviderInterfaceInterface.intf
  src/aura/dataProviderInterface/dataProviderInterfaceInterface.intf-meta.xml
Labels: Community

#4564 Community Contribution: Prevent exception on undefined trigger handler action
  src/classes/STG_PanelHealthCheck_CTRL.cls
  src/classes/STG_PanelHealthCheck_TEST.cls
  src/classes/STG_PanelTDTM_CTRL.cls
  src/classes/TDTM_ObjectDataGateway.cls
  src/classes/TDTM_ObjectDataGateway_TEST.cls
  src/classes/TDTM_ObjectDataGateway_TEST.cls-meta.xml
  src/package.xml
Labels: Community

#4562 RD2: New RecurringDonation and RecurringDonationSettings fields
  src/objects/npe03__Recurring_Donation__c.object
  src/objects/npe03__Recurring_Donations_Settings__c.object
  src/package.xml
Labels: Not-to-master

#4410 PYALLOCB: 1-B : Update Error Object and Err_Handler class
  ApexDocContent/ErrorHandling.htm
  src/classes/ERR_Handler.cls
  src/classes/ERR_RecordError.cls
  src/classes/ERR_RecordError.cls-meta.xml
  src/classes/ERR_RecordError_TEST.cls
  src/classes/ERR_RecordError_TEST.cls-meta.xml
  src/labels/CustomLabels.labels
  src/objects/Error__c.object
  src/package.xml
Labels: QE - Test

#4624 LQA Bug Fixes
  src/objectTranslations/Account-es.objectTranslation
  src/objectTranslations/Account-nl_NL.objectTranslation
  src/objectTranslations/Contact-nl_NL.objectTranslation
  src/objectTranslations/DataImportBatch__c-nl_NL.objectTranslation
  src/objectTranslations/DataImport__c-nl_NL.objectTranslation
  src/objectTranslations/Data_Import_Settings__c-nl_NL.objectTranslation
  src/objectTranslations/Engagement_Plan_Template__c-fr.objectTranslation
  src/objectTranslations/Opportunity-nl_NL.objectTranslation
  src/objectTranslations/npo02__Household__c-nl_NL.objectTranslation
  src/translations/de.translation
  src/translations/es.translation
  src/translations/fr.translation
  src/translations/ja.translation
  src/translations/nl_NL.translation
Labels: Not-to-master

#4635 Update Trialforce template Id
  orgs/trial.json
Labels: Infrastructure

#4639 Enhanced Recurring Donations "Start Date" field
  src/objectTranslations/npe03__Recurring_Donation__c-de.objectTranslation
  src/objectTranslations/npe03__Recurring_Donation__c-es.objectTranslation
  src/objectTranslations/npe03__Recurring_Donation__c-fr.objectTranslation
  src/objectTranslations/npe03__Recurring_Donation__c-iw.objectTranslation
  src/objectTranslations/npe03__Recurring_Donation__c-ja.objectTranslation
  src/objectTranslations/npe03__Recurring_Donation__c-nl_NL.objectTranslation
  src/objectTranslations/npe03__Recurring_Donations_Settings__c-de.objectTranslation
  src/objectTranslations/npe03__Recurring_Donations_Settings__c-es.objectTranslation
  src/objectTranslations/npe03__Recurring_Donations_Settings__c-fr.objectTranslation
  src/objectTranslations/npe03__Recurring_Donations_Settings__c-iw.objectTranslation
  src/objectTranslations/npe03__Recurring_Donations_Settings__c-ja.objectTranslation
  src/objectTranslations/npe03__Recurring_Donations_Settings__c-nl_NL.objectTranslation
  src/objects/npe03__Recurring_Donation__c.object
  src/package.xml
Labels: Not-to-master
