Repository SalesforceFoundation/NPSP, pull requests merged in 2019-06, with the labels that each got.

#4302 Update trial.json with NPSP 3.156
  orgs/trial.json
Labels: Infrastructure

#4247 Automated Bulk Data Import Testing
  .flake8
  .gitignore
  cumulusci.yml
  datasets/bdi_benchmark/mapping.yml
  robot/Cumulus/perftests/BDI_Tests.robot
  robot/Cumulus/resources/NPSP.py
  tasks/generate_bdi_data.py
  unpackaged/config/perf/objects/___NAMESPACE___DataImport__c.object
  unpackaged/config/perf/package.xml
Labels: Infrastructure

#4301 Psadie/bdi co migration utility preserve standard field mapping set
  src/classes/BDI_HelpTextCMT.cls
  src/classes/BDI_MigrationMappingHelper.cls
  src/classes/BDI_MigrationMappingUtility.cls
  src/classes/BDI_MigrationMappingUtilityTest.cls
  src/classes/STG_PanelDataImportAdvancedMapping_CTRL.cls
  src/labels/CustomLabels.labels
  src/package.xml
  src/pages/STG_PanelDataImportAdvancedMapping.page
Labels: Do Not Merge, Not-to-master

#4298 fix merge of contacts blanking affiliations
  src/classes/CON_ContactMerge_CTRL.cls
  src/classes/CON_ContactMerge_TEST2.cls
Labels: QE - Test

#4324 Changed text value for stgHelpAutoAffil
  src/labels/CustomLabels.labels
Labels: QE - Test

#4317 Telemetry: Add boolean feature parameter for tracking DI field mapping method
  src/classes/STG_SettingsService.cls
  src/classes/UTIL_OrgTelemetry_SVC.cls
  src/classes/UTIL_OrgTelemetry_TEST.cls
  src/featureParameters/IsEnabled_BDICMT.featureParameterBoolean
  src/package.xml
Labels: Not-to-master

#4307 Remove unnecessary DML when inserting a Contact with an Address and without an AccountId
  src/classes/ACCT_IndividualAccounts_TDTM.cls
  src/classes/ADDR_Account_TDTM.cls
  src/classes/ADDR_Addresses_TDTM.cls
  src/classes/ADDR_Addresses_TEST.cls
  src/classes/ADDR_Contact_TDTM.cls
  src/classes/TDTM_DMLgt200_TEST.cls
  src/classes/TDTM_TriggerHandler.cls
Labels: QE - Test

#4312 Enable non-default Account Soft Credit fields in Customizable Rollups
  src/aura/CRLP_Rollup/CRLP_RollupController.js
  src/aura/CRLP_Rollup/CRLP_RollupHelper.js
  src/classes/CRLP_RollupUI_SVC.cls
Labels: QE - Test
