Repository SalesforceFoundation/NPSP, pull requests merged in 2020-08, with the labels that each got.

#5704 Gift Entry: fix namespace retrieval bug in elevate field bundle
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
Labels: bug

#5707 LQA fixes for summer20 drop1
  cumulusci.yml
  src/objectTranslations/Campaign-de.objectTranslation
  src/objectTranslations/Campaign-es.objectTranslation
  src/objectTranslations/Campaign-fr.objectTranslation
  src/objectTranslations/Campaign-ja.objectTranslation
  src/objectTranslations/Campaign-nl_NL.objectTranslation
  src/objectTranslations/DataImportBatch__c-de.objectTranslation
  src/objectTranslations/DataImportBatch__c-en_US.objectTranslation
  src/objectTranslations/DataImportBatch__c-es.objectTranslation
  src/objectTranslations/DataImportBatch__c-fr.objectTranslation
  src/objectTranslations/DataImportBatch__c-iw.objectTranslation
  src/objectTranslations/DataImportBatch__c-ja.objectTranslation
  src/objectTranslations/DataImportBatch__c-nl_NL.objectTranslation
  src/objectTranslations/RecurringDonationSchedule__c-fr.objectTranslation
  src/objectTranslations/npe03__Recurring_Donation__c-fr.objectTranslation
  src/objectTranslations/npe03__Recurring_Donation__c-nl_NL.objectTranslation
  src/translations/de.translation
  src/translations/es.translation
  src/translations/fr.translation
  src/translations/iw.translation
  src/translations/ja.translation
  src/translations/nl_NL.translation
  unpackaged/config/rd2_post_config/objectTranslations/npe03__Recurring_Donation__c-fr.objectTranslation
  unpackaged/config/rd2_post_config/objectTranslations/npe03__Recurring_Donation__c-nl_NL.objectTranslation
Labels: Not-to-master

#5712 Update Opportunity Naming sharing from "with sharing" to "inherited sharing"
  src/classes/OPP_OpportunityNaming.cls
Labels: bug

#5725 RD2: Exclude paused installments from calculations
  cumulusci.yml
  src/classes/RD2_OpportunityEvaluationService.cls
  src/classes/RD2_OpportunityEvaluationService_TEST.cls
  src/classes/RD2_OpportunityEvaluation_TEST.cls
  src/classes/RD2_OpportunityService.cls
  src/classes/RD2_PauseForm_CTRL.cls
  src/classes/RD2_PauseForm_TEST.cls
  src/classes/RD2_QueueableService.cls
  src/classes/RD2_RecurringDonationsOpp_TDTM.cls
  src/classes/RD2_RecurringDonationsOpp_TEST.cls
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/RD2_RecurringDonations_TEST.cls
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/classes/RD2_VisualizeScheduleController.cls
  src/classes/TEST_SObjectGateway.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master, QE - Test

#5728 RD2: Prevent Elevate RD to be Paused
  src/classes/RD2_ElevateIntegrationService_TEST.cls
  src/classes/RD2_PauseForm_CTRL.cls
  src/classes/RD2_PauseForm_TEST.cls
  src/labels/CustomLabels.labels
  src/lwc/rd2PauseForm/rd2PauseForm.html
  src/lwc/rd2PauseForm/rd2PauseForm.js
  src/package.xml
Labels: Not-to-master

#5737 RD2: Display the first donation date after the pause ends
  src/classes/RD2_PauseForm_CTRL.cls
  src/lwc/rd2PauseForm/rd2PauseForm.html
  src/lwc/rd2PauseForm/rd2PauseForm.js
Labels: Not-to-master

#5720 Remove display limit of 75 Payment Fields on NPSP Settings | Donations | Payment Mappings
  src/classes/STG_PanelPaymentMapping_CTRL.cls
Labels: QE - Test

#5688 Set hasSampleData to `false` for all scratch org definitions
  orgs/beta.json
  orgs/beta_middlesuffix.json
  orgs/beta_multicurrency.json
  orgs/beta_nonenglish.json
  orgs/beta_personaccounts.json
  orgs/beta_platformencryption.json
  orgs/beta_prerelease.json
  orgs/beta_statecountry.json
  orgs/dev.json
  orgs/dev_multicurrency.json
  orgs/enterprise.json
  orgs/feature.json
  orgs/prerelease.json
  orgs/release.json
  robot/Cumulus/tests/browser/contacts_accounts/create_organization.robot
Labels: Infrastructure

#5745 Feature/jest config
  .github/CODEOWNERS
  .github/workflows/jest.yml
  .gitignore
  jest.config.js
  jest.setup.js
  package.json
  sfdx-project.json
  src/lwc/utilIllustration/__tests__/utilIllustration.test.js
  yarn.lock
Labels: Infrastructure

#5449 Fix migration utility legacy object name check
  src/classes/BDI_MigrationMappingHelper.cls
  src/classes/BDI_MigrationMappingUtility.cls
Labels: bug

#5770 Option To Disable Record Data Health Check
  src/classes/STG_PanelHealthCheck_CTRL.cls
  src/classes/STG_SettingsManager_TEST.cls
  src/classes/UTIL_CustomSettingsFacade.cls
  src/labels/CustomLabels.labels
  src/objects/Error_Settings__c.object
  src/package.xml
  src/pages/STG_PanelHealthCheck.page
  src/translations/es.translation
  src/translations/fr.translation
  src/translations/iw.translation
  src/translations/ja.translation
  src/translations/nl_NL.translation
Labels: QE - Test
