Repository SalesforceFoundation/NPSP, pull requests merged in 2020-05, with the labels that each got.

#5397 GE PMT: Clear out Payment Status and Token in 'Do Not Charge Card' Mode
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
  src/lwc/geGiftEntryFormApp/geGiftEntryFormApp.js
Labels: Not-to-master

#5391 GE PMT: Exclude field mappings by source api name
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.js
Labels: Not-to-master

#5423 DataSet: RD2 Pilot Testing LDV Org Snowfakery Config
  datasets/rd2_pilot/rd_ldv_factory.yml
Labels: Infrastructure

#5392 RD2: Validate RD status to state mapping
  src/classes/RD2_StatusMapper.cls
  src/classes/RD2_StatusMapper.cls-meta.xml
  src/classes/RD2_StatusMapper_TEST.cls
  src/classes/RD2_StatusMapper_TEST.cls-meta.xml
  src/classes/RD2_ValidationService.cls
  src/classes/RD2_ValidationService_TEST.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master

#5401 RD2: Status Mapping Health Check
  src/classes/RD2_RecurringDonation.cls
  src/classes/RD2_StatusMapper.cls
  src/classes/RD2_StatusMapper_TEST.cls
  src/classes/RD2_ValidationService.cls
  src/classes/STG_PanelRDHealthCheck.cls
  src/classes/STG_PanelRDHealthCheck_TEST.cls
  src/labels/CustomLabels.labels
Labels: Not-to-master

#5448 RD2: Fix Test Class Failure
  src/classes/RD2_ValidationService.cls
  src/classes/RD2_ValidationService_TEST.cls
Labels: Not-to-master

#5430 [Robot]Page Object For Customizable Rollups
  robot/Cumulus/resources/CustomizableRollupsPageObject.py
  robot/Cumulus/resources/locators_48.py
Labels: WIP

#5410 RD2: Status to State Functionality
  src/classes/RD2_ElevateIntegrationService.cls
  src/classes/RD2_OpportunityEvaluationService_TEST.cls
  src/classes/RD2_RecurringDonation.cls
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/classes/RD2_StatusMapper_TEST.cls
  src/classes/RD2_ValidationService.cls
  src/classes/RD2_VisualizeScheduleController.cls
  src/classes/RD2_VisualizeScheduleController_TEST.cls
Labels: Not-to-master

#4675 Update Trailhead Installer
  cumulusci.yml
  datasets/trailhead/mapping.yml
  datasets/trailhead/test_data.sql
  lib/trailhead_admin_profile.xml
  unpackaged/config/trailhead/layouts/Campaign-Campaign Layout.layout
  unpackaged/config/trailhead/layouts/Campaign-npsp__NPSP Campaign Layout.layout
  unpackaged/config/trailhead/layouts/Contact-Contact Lightning Layout.layout
  unpackaged/config/trailhead/layouts/Contact-npsp__Contact Layout.layout
  unpackaged/config/trailhead/objects/Campaign.object
  unpackaged/config/trailhead/objects/Contact.object
  unpackaged/config/trailhead/objects/npe4__Relationship__c.object
  unpackaged/config/trailhead/package.xml
  unpackaged/config/trailhead/profiles/Admin.profile
  unpackaged/config/trailhead/standardValueSets/CampaignType.standardValueSet
  unpackaged/config/trailhead_delete/destructiveChanges.xml
  unpackaged/config/trailhead_delete/package.xml
Labels: Infrastructure

#5411 RD2: Status to state mapping page and config
  StaticResourceSources/customDatatable/style.css
  src/aura/RD2_EnablementApp/RD2_EnablementApp.app
  src/classes/RD2_OpportunityEvaluationService_TEST.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/classes/RD2_StatusMapper.cls
  src/classes/RD2_StatusMapper_TEST.cls
  src/classes/RD2_StatusMappingSettings_CTRL.cls
  src/classes/RD2_StatusMappingSettings_CTRL.cls-meta.xml
  src/classes/RD2_StatusMappingSettings_TEST.cls
  src/classes/RD2_StatusMappingSettings_TEST.cls-meta.xml
  src/classes/RD2_ValidationService_TEST.cls
  src/classes/RD2_VisualizeScheduleController_TEST.cls
  src/classes/STG_PanelRDHealthCheck_TEST.cls
  src/classes/UTIL_CustomSettingsFacade.cls
  src/labels/CustomLabels.labels
  src/layouts/RecurringDonationStatusMapping__mdt-Recurring Donation Status Mapping Layout.layout
  src/lwc/customDatatable/customDatatable.js
  src/lwc/customDatatable/customDatatable.js-meta.xml
  src/lwc/customDatatable/picklistTypeTemplate.html
  src/lwc/customPicklistType/customPicklistType.html
  src/lwc/customPicklistType/customPicklistType.js
  src/lwc/customPicklistType/customPicklistType.js-meta.xml
  src/lwc/rd2StatusMappingSettings/rd2StatusMappingSettings.css
  src/lwc/rd2StatusMappingSettings/rd2StatusMappingSettings.html
  src/lwc/rd2StatusMappingSettings/rd2StatusMappingSettings.js
  src/lwc/rd2StatusMappingSettings/rd2StatusMappingSettings.js-meta.xml
  src/objectTranslations/RecurringDonationStatusMapping__mdt-de.objectTranslation
  src/objectTranslations/RecurringDonationStatusMapping__mdt-en_US.objectTranslation
  src/objectTranslations/RecurringDonationStatusMapping__mdt-es.objectTranslation
  src/objectTranslations/RecurringDonationStatusMapping__mdt-fr.objectTranslation
  src/objectTranslations/RecurringDonationStatusMapping__mdt-iw.objectTranslation
  src/objectTranslations/RecurringDonationStatusMapping__mdt-ja.objectTranslation
  src/objectTranslations/RecurringDonationStatusMapping__mdt-nl_NL.objectTranslation
  src/objects/RecurringDonationStatusMapping__mdt.object
  src/objects/npe03__Recurring_Donations_Settings__c.object
  src/package.xml
  src/pages/STG_PanelRD2Enablement.page
  src/pages/STG_PanelRD2StatusMapping.page
  src/pages/STG_PanelRD2StatusMapping.page-meta.xml
  src/pages/STG_SettingsManager.page
  src/staticresources/CumulusStaticResources.resource
  unpackaged/config/rd2_post_config/profiles/Admin.profile
  unpackaged/config/rd2_post_config/profiles/Standard.profile
Labels: Not-to-master

#5484 Callable API: Enable RD2
  cumulusci.yml
  src/classes/CallableApiParameters.cls
  src/classes/Callable_API.cls
  src/classes/Callable_API_TEST.cls
  src/classes/RD2_EnablementDelegate_CTRL.cls
  src/classes/RD2_EnablementDelegate_TEST.cls
  src/classes/RD2_EnablementService.cls
  src/classes/RD2_EnablementService_TEST.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: QE - Test

#5480 [Robot] crlp testcase for last soft credit opportunity
  robot/Cumulus/resources/CustomizableRollupsPageObject.py
  robot/Cumulus/resources/NPSP.py
  robot/Cumulus/resources/NPSP.robot
  robot/Cumulus/resources/NPSPSettingsPageObject.py
  robot/Cumulus/resources/ObjectMangerPageObject.py
  robot/Cumulus/resources/OpportunityPageObject.py
  robot/Cumulus/resources/locators_48.py
  robot/Cumulus/tests/browser/crlps/last_soft_credit_opportunity.robot
Labels: WIP

#5509 RD2: Entry Form
  src/aura/RD2_EntryForm/RD2_EntryForm.cmp
  src/aura/RD2_EntryForm/RD2_EntryForm.cmp-meta.xml
  src/aura/RD2_EntryForm/RD2_EntryForm.css
  src/aura/RD2_EntryForm/RD2_EntryFormController.js
  src/aura/RD2_EntryForm/RD2_EntryFormHelper.js
  src/classes/RD2_EntryFormController.cls
  src/classes/RD2_EntryFormController.cls-meta.xml
  src/classes/RD2_EntryFormController_TEST.cls
  src/classes/RD2_EntryFormController_TEST.cls-meta.xml
  src/labels/CustomLabels.labels
  src/lwc/rd2EntryForm/rd2EntryForm.html
  src/lwc/rd2EntryForm/rd2EntryForm.js
  src/lwc/rd2EntryForm/rd2EntryForm.js-meta.xml
  src/lwc/utilPageLevelMessage/utilPageLevelMessage.js
  src/package.xml
  unpackaged/config/rd2_post_config/objects/npe03__Recurring_Donation__c.object
Labels: Not-to-master

#5524 Api48: Reset GE and FORM class versions
  src/aura/BDI_ManageAdvancedMapping/BDI_ManageAdvancedMapping.cmp-meta.xml
  src/aura/BGE_BatchGiftEntryTab/BGE_BatchGiftEntryTab.cmp-meta.xml
  src/aura/BGE_ConfigurationWizard/BGE_ConfigurationWizard.cmp-meta.xml
  src/aura/BGE_DataImportBatchEntry/BGE_DataImportBatchEntry.cmp-meta.xml
  src/aura/BGE_DonationSelector/BGE_DonationSelector.cmp-meta.xml
  src/aura/BGE_EntryForm/BGE_EntryForm.cmp-meta.xml
  src/aura/GE_GiftEntry/GE_GiftEntry.cmp-meta.xml
  src/aura/GE_GiftEntryForm/GE_GiftEntryForm.cmp-meta.xml
  src/aura/GE_TemplateBuilder/GE_TemplateBuilder.cmp-meta.xml
  src/classes/FORM_BatchHeaderField.cls-meta.xml
  src/classes/FORM_Element.cls-meta.xml
  src/classes/FORM_Layout.cls-meta.xml
  src/classes/FORM_PermissionValidator.cls-meta.xml
  src/classes/FORM_PermissionsValidator_TEST.cls-meta.xml
  src/classes/FORM_RenderWrapper.cls-meta.xml
  src/classes/FORM_Section.cls-meta.xml
  src/classes/FORM_Service.cls-meta.xml
  src/classes/FORM_ServiceGiftEntry.cls-meta.xml
  src/classes/FORM_ServiceGiftEntry_TEST.cls-meta.xml
  src/classes/FORM_Template.cls-meta.xml
  src/classes/GE_DefaultTemplate.cls-meta.xml
  src/classes/GE_DefaultTemplate_TEST.cls-meta.xml
  src/classes/GE_FormRendererService.cls-meta.xml
  src/classes/GE_FormRendererService_TEST.cls-meta.xml
  src/classes/GE_FormServiceController.cls-meta.xml
  src/classes/GE_GiftEntryController.cls-meta.xml
  src/classes/GE_GiftEntryController_TEST.cls-meta.xml
  src/classes/GE_GiftEntry_UTIL.cls-meta.xml
  src/classes/GE_LookupController.cls-meta.xml
  src/classes/GE_LookupController_TEST.cls-meta.xml
  src/classes/GE_TemplateBuilderCtrl.cls-meta.xml
Labels: Not-to-master
