Repository SalesforceFoundation/NPSP, pull requests merged in 2020-04, with the labels that each got.

#5285 RD2: Health Check allows Day of Month picklist values of 29 and 30
  src/classes/STG_PanelRDHealthCheck.cls
  src/classes/STG_PanelRDHealthCheck_TEST.cls
Labels: Not-to-master

#5288 RD2: Metadata keeps Day of Month values of 29 and 30 as active
  unpackaged/config/rd2_post_config/objects/npe03__Recurring_Donation__c.object
Labels: Not-to-master

#5286 RD2: Data Migration handles Day of Month values of 29 and 30
  src/classes/RD2_DataMigrationMapper.cls
  src/classes/RD2_DataMigration_TEST.cls
  src/classes/RD2_ValidationService.cls
  src/classes/RD2_ValidationService_TEST.cls
  src/labels/CustomLabels.labels
  src/objects/RecurringDonationSchedule__c.object
Labels: Not-to-master

#5279 Gift Entry: Purchase call
  src/classes/GE_GiftEntryController.cls
  src/classes/GE_GiftEntryController_TEST.cls
  src/classes/GE_PaymentServices.cls
  src/classes/GE_PaymentServices_TEST.cls
  src/classes/GE_PaymentServices_TEST.cls-meta.xml
  src/labels/CustomLabels.labels
  src/layouts/DataImport__c-Data Import Layout.layout
  src/lwc/geFormRenderer/geFormRenderer.css
  src/lwc/geFormRenderer/geFormRenderer.html
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geFormService/geFormService.js
  src/lwc/geFormWidget/geFormWidget.html
  src/lwc/geFormWidget/geFormWidget.js
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.css
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.html
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
  src/lwc/geGiftEntryFormApp/geGiftEntryFormApp.html
  src/lwc/geGiftEntryFormApp/geGiftEntryFormApp.js
  src/lwc/geLabelService/geLabelService.js
  src/lwc/utilCommon/utilCommon.js
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
  src/objects/DataImport__c.object
  src/package.xml
  src/pages/GE_TokenizeCard.page
Labels: Not-to-master

#5309 Gift Entry: fix bad reference to CUSTOM_LABELS property
  src/lwc/geGiftEntryFormApp/geGiftEntryFormApp.js
Labels: Not-to-master

#5310 Gift Entry: fixes for WI-039749
  src/lwc/geFormRenderer/geFormRenderer.js
Labels: Not-to-master

#5302 RD2: Schedule Service Handles DayOfMonth 29 and 30 - part 2
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/classes/RD2_ValidationService_TEST.cls
Labels: Not-to-master

#5316 Gift Entry: Fixes for Submit tokenized payment information for processing
  src/lwc/geGiftEntryFormApp/geGiftEntryFormApp.js
Labels: Not-to-master

#5294 Enhanced Recurring Donations: Support for Expanded DayOfMonth values
  src/classes/RD2_DataMigrationMapper.cls
  src/classes/RD2_DataMigration_TEST.cls
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/classes/RD2_ValidationService.cls
  src/classes/RD2_ValidationService_TEST.cls
  src/classes/STG_PanelRDHealthCheck.cls
  src/classes/STG_PanelRDHealthCheck_TEST.cls
  src/labels/CustomLabels.labels
  src/objects/RecurringDonationSchedule__c.object
  unpackaged/config/rd2_post_config/objects/npe03__Recurring_Donation__c.object
Labels: QE - Test

#5339 Gift Entry: Hide Credit Card Widget in Batch Mode
  src/lwc/geFormRenderer/geFormRenderer.js
Labels: Not-to-master

#5333 RD2: Find matching Opps by CommitmentId
  src/classes/ERR_Handler_API.cls
  src/classes/RD2_ElevateIntegrationService.cls
  src/classes/RD2_ElevateIntegrationService.cls-meta.xml
  src/classes/RD2_ElevateIntegrationService_TEST.cls
  src/classes/RD2_ElevateIntegrationService_TEST.cls-meta.xml
  src/classes/RD2_QueueableService.cls
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/TEST_OpportunityBuilder.cls
  src/classes/TEST_RecurringDonationBuilder.cls
  src/classes/TEST_SObjectGateway.cls
  src/objects/Opportunity.object
  src/package.xml
Labels: QE - Test

#5301 CCI: Update Deploy_Rd2_Testing flow
  cumulusci.yml
Labels: Infrastructure

#5374 GE PMT: handle system errors
  src/aura/GE_GiftEntryForm/GE_GiftEntryForm.cmp
  src/aura/GE_GiftEntryForm/GE_GiftEntryFormController.js
  src/classes/ERR_Handler_API.cls
  src/classes/GE_GiftEntryController.cls
  src/classes/GE_PaymentServices.cls
  src/labels/CustomLabels.labels
  src/lwc/geConstants/geConstants.js
  src/lwc/geFormRenderer/geFormRenderer.css
  src/lwc/geFormRenderer/geFormRenderer.html
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geFormWidget/geFormWidget.js
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.css
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.html
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
  src/lwc/geGiftEntryFormApp/geGiftEntryFormApp.html
  src/lwc/geGiftEntryFormApp/geGiftEntryFormApp.js
  src/lwc/geLabelService/geLabelService.js
  src/lwc/geListView/geListView.js
  src/lwc/gePurchaseCallModalError/gePurchaseCallModalError.css
  src/lwc/gePurchaseCallModalError/gePurchaseCallModalError.html
  src/lwc/gePurchaseCallModalError/gePurchaseCallModalError.js
  src/lwc/gePurchaseCallModalError/gePurchaseCallModalError.js-meta.xml
  src/lwc/utilCommon/utilCommon.js
  src/lwc/utilCustomErrors/cardChargedBDIError.js
  src/lwc/utilCustomErrors/exceptionDataError.js
  src/lwc/utilCustomErrors/httpRequestError.js
  src/lwc/utilCustomErrors/utilCustomErrors.js
  src/lwc/utilCustomErrors/utilCustomErrors.js-meta.xml
  src/lwc/utilIllustration/utilIllustration.html
  src/lwc/utilIllustration/utilIllustration.js
  src/lwc/utilNumberFormatter/utilNumberFormatter.js
  src/lwc/utilNumberFormatter/utilNumberFormatter.js-meta.xml
  src/package.xml
  src/pages/GE_TokenizeCard.page
Labels: Not-to-master

#5393 GE PMT: Add 'Do Not Charge Card' feature to Payments widget
  src/labels/CustomLabels.labels
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.css
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.html
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
  src/lwc/geLabelService/geLabelService.js
  src/package.xml
Labels: Not-to-master

#5399 GE PMT: Minor updates to description and error message
  src/labels/CustomLabels.labels
  src/objects/DataImport__c.object
Labels: Not-to-master

#5343 [Robot]Enhancement to Regression tests to work with CRLP setting on
  robot/Cumulus/resources/NPSP.robot
  robot/Cumulus/resources/NPSPSettingsPageObject.py
  robot/Cumulus/tests/browser/recurring_donations/create_a_fixed_length_recurring_donation_multiply_by.robot
  robot/Cumulus/tests/browser/recurring_donations/create_recurring_donation_and_check_rollups.robot
Labels: Test Automation
