Repository SalesforceFoundation/NPSP, pull requests merged in 2020-12, with the labels that each got.

#6081 [GS][W-7976392] Change button label
  src/labels/CustomLabels.labels
Labels: Nonprofit-Optimize, Not-to-master

#6080 [GS][W-8515435] Add 'WITH SECURITY_ENFORCED' to SOQL
  src/classes/GS_AdminSetup.cls
Labels: Nonprofit-Optimize, Not-to-master

#6073 Gift Entry: Handle 230 URL Formats
  src/lwc/psElevateTokenHandler/__tests__/psElevateTokenHandler.test.js
  src/lwc/psElevateTokenHandler/psElevateTokenHandler.js
Labels: Not-to-master

#6088 [GETTING STARTED] Fixing failing test
  src/classes/GS_ApplicationStatusController_TEST.cls
  src/classes/UTIL_FeatureManagement_TEST.cls
Labels: Nonprofit-Optimize

#6083 Gift Entry: Display ACH fields in Salesforce.org Elevate field bundle
  src/labels/CustomLabels.labels
  src/lwc/geFormRenderer/geFormRenderer.html
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geFormSection/geFormSection.html
  src/lwc/geFormSection/geFormSection.js
  src/lwc/geFormWidget/geFormWidget.html
  src/lwc/geFormWidget/geFormWidget.js
  src/lwc/geFormWidgetTokenizeCard/__tests__/geFormWidgetTokenizeCard.test.js
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.css
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.html
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
  src/lwc/geLabelService/geLabelService.js
  src/lwc/psElevateTokenHandler/psElevateTokenHandler.js
  src/lwc/rd2ElevateCreditCardForm/rd2ElevateCreditCardForm.css
  src/lwc/rd2ElevateCreditCardForm/rd2ElevateCreditCardForm.js
  src/lwc/rd2EntryForm/rd2EntryForm.html
  src/lwc/rd2EntryForm/rd2EntryForm.js
  src/package.xml
  src/pages/GE_TokenizeCard.page
Labels: Not-to-master

#6100 [RD] Prevent concurrent RD batch jobs
  src/classes/RD2_OpportunityEvaluation_BATCH.cls
  src/classes/RD2_OpportunityEvaluation_TEST.cls
  src/classes/RD_RecurringDonations_BATCH.cls
  src/classes/RD_RecurringDonations_TEST2.cls
  src/classes/STG_PanelRDBatch_CTRL.cls
  src/classes/UTIL_BatchJobService.cls
Labels: QE - Test

#6105 [GS][W-8522922] Change in 'Adjust NPSP Settings' item
  src/classes/GS_ChecklistSetup.cls
  src/customMetadata/GetStartedChecklistItem.NPSP_Settings.md
  src/labels/CustomLabels.labels
  src/lwc/gsChecklistItem/gsChecklistItem.js
  src/lwc/gsLabelMapper/gsLabelMapper.js
  src/package.xml
Labels: Nonprofit-Optimize

#6117 [GS][W-8486415] Add Resources Videography
  src/labels/CustomLabels.labels
  src/lwc/gsResources/gsResources.js
  src/package.xml
Labels: Nonprofit-Optimize

#6099 Feature/dcaballero/gs accessibility
  src/lwc/gsChecklistItem/gsChecklistItem.js
Labels: Nonprofit-Optimize

#6111 Feature/dcaballero/gs labels change
  StaticResourceSources/gsAssets/Get_started_header.svg
  src/labels/CustomLabels.labels
  src/lwc/gsVideoHeader/gsVideoHeader.css
  src/lwc/gsVideoHeader/gsVideoHeader.html
  src/lwc/gsVideoHeader/gsVideoHeader.js
  src/staticresources/CumulusStaticResources.resource
Labels: Nonprofit-Optimize

#6112 Gift Entry: Integrate Payment Widget for SGE ACH
  src/classes/BDI_DataImportService.cls
  src/classes/GE_PaymentServices.cls
  src/lwc/geConstants/geConstants.js
  src/lwc/geFormRenderer/geFormRenderer.html
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geFormSection/geFormSection.js
  src/lwc/geFormWidget/geFormWidget.js
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
  src/lwc/psElevateTokenHandler/psElevateTokenHandler.js
  src/lwc/rd2ElevateCreditCardForm/rd2ElevateCreditCardForm.js
  src/pages/GE_TokenizeCard.page
Labels: Not-to-master

#6104 [GS][W-8529083] Add 'Page Type' field to section metadata
  src/classes/GS_ChecklistSetup.cls
  src/classes/GS_ChecklistSetup_TEST.cls
  src/customMetadata/GetStartedChecklistSection.Bring_Users_Onboard.md
  src/customMetadata/GetStartedChecklistSection.Explore_NPSP.md
  src/customMetadata/GetStartedChecklistSection.Make_it_your_own.md
  src/flexipages/GetStarted.flexipage
  src/layouts/GetStartedChecklistSection__mdt-GS Checklist Section Layout.layout
  src/lwc/gsChecklistSetup/gsChecklistSetup.js
  src/lwc/gsChecklistSetup/gsChecklistSetup.js-meta.xml
  src/lwc/gsResources/gsResources.js
  src/lwc/gsResources/gsResources.js-meta.xml
  src/objectTranslations/GetStartedChecklistSection__mdt-de.objectTranslation
  src/objectTranslations/GetStartedChecklistSection__mdt-en_US.objectTranslation
  src/objectTranslations/GetStartedChecklistSection__mdt-es.objectTranslation
  src/objectTranslations/GetStartedChecklistSection__mdt-fr.objectTranslation
  src/objectTranslations/GetStartedChecklistSection__mdt-iw.objectTranslation
  src/objectTranslations/GetStartedChecklistSection__mdt-ja.objectTranslation
  src/objectTranslations/GetStartedChecklistSection__mdt-nl_NL.objectTranslation
  src/objects/GetStartedChecklistSection__mdt.object
  src/package.xml
Labels: Nonprofit-Optimize

#6133 [GS] Removed required property to Page_type GsSection
  src/objects/GetStartedChecklistSection__mdt.object
  src/package.xml
Labels: Nonprofit-Optimize

#6139 Removed ACH help icons
  src/pages/GE_TokenizeCard.page
Labels: Not-to-master

#6146 Update text on Elevate widget in template builder
  src/labels/CustomLabels.labels
  src/lwc/geLabelService/geLabelService.js
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.html
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.js
  src/lwc/geTemplateBuilderWidget/geTemplateBuilderWidget.html
  src/package.xml
Labels: Not-to-master
