Repository SalesforceFoundation/NPSP, pull requests merged in 2020-07, with the labels that each got.

#5609 RD2: Custom Field Section UI
  src/aura/RD2_EntryForm/RD2_EntryForm.cmp
  src/classes/RD2_EntryFormController.cls
  src/classes/RD2_EntryFormController_TEST.cls
  src/lwc/rd2EntryForm/rd2EntryForm.html
  src/lwc/rd2EntryForm/rd2EntryForm.js
  src/lwc/rd2EntryFormCustomFieldsSection/rd2EntryFormCustomFieldsSection.html
  src/lwc/rd2EntryFormCustomFieldsSection/rd2EntryFormCustomFieldsSection.js
  src/lwc/rd2EntryFormCustomFieldsSection/rd2EntryFormCustomFieldsSection.js-meta.xml
  src/objects/npe03__Recurring_Donation__c.object
  src/package.xml
Labels: Not-to-master

#5599 RD2 UI: Advanced Scheduling
  src/classes/RD2_EntryFormController.cls
  src/classes/RD2_EntryFormController_TEST.cls
  src/labels/CustomLabels.labels
  src/lwc/rd2EntryForm/rd2EntryForm.css
  src/lwc/rd2EntryForm/rd2EntryForm.html
  src/lwc/rd2EntryForm/rd2EntryForm.js
  src/lwc/rd2EntryFormDonorSection/rd2EntryFormDonorSection.css
  src/lwc/rd2EntryFormDonorSection/rd2EntryFormDonorSection.html
  src/lwc/rd2EntryFormDonorSection/rd2EntryFormDonorSection.js
  src/lwc/rd2EntryFormScheduleSection/rd2EntryFormScheduleSection.css
  src/lwc/rd2EntryFormScheduleSection/rd2EntryFormScheduleSection.html
  src/lwc/rd2EntryFormScheduleSection/rd2EntryFormScheduleSection.js
  src/package.xml
Labels: Not-to-master, QE - Test

#5636 RD: NPSP Setting RD Naming Format
  src/classes/STG_PanelRD_CTRL.cls
  src/classes/STG_SettingsManager_TEST.cls
  src/pages/STG_PanelRD.page
Labels: QE - Test

#5665 Gift Entry: Fix edit mode review donations bug
  src/classes/GE_FormRendererService.cls
  src/lwc/geFormRenderer/geFormRenderer.html
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geReviewDonations/geReviewDonations.html
  src/lwc/geReviewDonations/geReviewDonations.js
  src/lwc/utilCard/utilCard.html
Labels: bug

#5692 Gift Entry: Record type name as text in batch gifts table
  src/lwc/geBatchGiftEntryTable/geBatchGiftEntryTable.js
Labels: bug

#5686 GE: Fix for Batch Processing bug
  src/lwc/geBatchWizard/geBatchWizard.js
  src/lwc/utilCommon/utilCommon.js
Labels: bug

#5682 RD2: Create and edit Pause on Recurring Donation
  src/aura/RD2_PauseForm/RD2_PauseForm.cmp
  src/aura/RD2_PauseForm/RD2_PauseForm.cmp-meta.xml
  src/aura/RD2_PauseForm/RD2_PauseFormController.js
  src/aura/RD2_PauseForm/RD2_PauseFormHelper.js
  src/classes/RD2_OpportunityEvaluationService.cls
  src/classes/RD2_PauseForm_CTRL.cls
  src/classes/RD2_PauseForm_CTRL.cls-meta.xml
  src/classes/RD2_PauseForm_TEST.cls
  src/classes/RD2_PauseForm_TEST.cls-meta.xml
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/classes/RD2_VisualizeScheduleController.cls
  src/classes/RD2_VisualizeScheduleController_TEST.cls
  src/classes/TEST_SObjectGateway.cls
  src/labels/CustomLabels.labels
  src/layouts/RecurringDonationSchedule__c-Recurring Schedule Layout.layout
  src/lwc/rd2PauseForm/rd2PauseForm.html
  src/lwc/rd2PauseForm/rd2PauseForm.js
  src/lwc/rd2PauseForm/rd2PauseForm.js-meta.xml
  src/lwc/rdScheduleVisualizer/rdScheduleVisualizer.html
  src/lwc/rdScheduleVisualizer/rdScheduleVisualizer.js
  src/objects/RecurringDonationSchedule__c.object
  src/package.xml
  src/quickActions/npe03__Recurring_Donation__c.Pause.quickAction
  unpackaged/config/rd2_post_config/layouts/npe03__Recurring_Donation__c-Enhanced Recurring Donations Layout.layout
  unpackaged/config/rd2_post_config/profiles/Admin.profile
  unpackaged/config/rd2_post_config/profiles/Standard.profile
Labels: Not-to-master, QE - Test
