Repository SalesforceFoundation/NPSP, pull requests merged in 2020-10, with the labels that each got.

#5897 RD2: Set Elevate Recurring Id on the new Recurring Donation
  src/classes/PS_CommitmentRequest.cls
  src/classes/PS_Request_TEST.cls
  src/classes/RD2_ElevateIntegrationService.cls
  src/classes/RD2_ElevateIntegrationService_TEST.cls
  src/classes/RD2_EntryFormController.cls
  src/classes/RD2_EntryFormController_TEST.cls
  src/classes/TEST_SObjectGateway.cls
  src/classes/UTIL_String.cls
  src/classes/UTIL_String_TEST.cls
  src/labels/CustomLabels.labels
  src/lwc/rd2EntryForm/rd2EntryForm.js
  src/objects/npe03__Recurring_Donation__c.object
  src/package.xml
  unpackaged/config/rd2_post_config/layouts/npe03__Recurring_Donation__c-Enhanced Recurring Donations Layout.layout
  unpackaged/config/rd2_post_config/profiles/Admin.profile
  unpackaged/config/rd2_post_config/profiles/Standard.profile
Labels: Not-to-master

#5907 RD2: Handle Cancel and Save buttons on save/error
  src/classes/RD2_EntryFormController.cls
  src/classes/RD2_EntryFormController_TEST.cls
  src/lwc/rd2EntryForm/rd2EntryForm.html
  src/lwc/rd2EntryForm/rd2EntryForm.js
Labels: Not-to-master

#5901 RD2: Prevent a Canceled Elevate RD from being re-activated
  src/classes/RD2_ElevateIntegrationService.cls
  src/classes/RD2_ElevateIntegrationService_TEST.cls
  src/classes/RD2_ValidationService.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master

#5905 [RD2] CallableApi action to Retrieve Schedule Records
  src/classes/CallableApiParameters.cls
  src/classes/CallableApiParameters_TEST.cls
  src/classes/Callable_API.cls
  src/classes/RD2_ApiService.cls
  src/classes/RD2_ApiService.cls-meta.xml
  src/classes/RD2_ApiService_TEST.cls
  src/classes/RD2_ApiService_TEST.cls-meta.xml
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/package.xml
Labels: QE - Test

#5906 RD2: Handle cancel commitment errors
  src/classes/PS_Request_TEST.cls
  src/classes/RD2_ElevateIntegrationService.cls
  src/classes/RD2_ElevateIntegrationService_TEST.cls
  src/classes/UTIL_Http.cls
  src/classes/UTIL_Http_TEST.cls
Labels: Not-to-master, QE - Test

#5877 RD2: Cancel Elevate Recurring Commitment
  src/classes/PS_IntegrationServiceConfig.cls
  src/classes/PS_IntegrationServiceConfig_TEST.cls
  src/classes/PS_Request.cls
  src/classes/PS_Request.cls-meta.xml
  src/classes/PS_Request_TEST.cls
  src/classes/PS_Request_TEST.cls-meta.xml
  src/classes/RD2_ElevateIntegrationService.cls
  src/classes/RD2_ElevateIntegrationService_TEST.cls
  src/classes/RD2_QueueableService.cls
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/RD2_RecurringDonations_TEST.cls
  src/classes/RD2_ValidationService.cls
  src/classes/RD2_ValidationService_TEST.cls
  src/classes/TDTM_ProcessControl.cls
  src/classes/UTIL_Http.cls
  src/classes/UTIL_Http.cls-meta.xml
  src/classes/UTIL_Http_TEST.cls
  src/classes/UTIL_Http_TEST.cls-meta.xml
  src/labels/CustomLabels.labels
  src/package.xml
Labels: WIP

#5936 GE, RD2: Consolidate common payments services code
  src/classes/GE_GiftEntryController.cls
  src/classes/GE_GiftEntryController_TEST.cls
  src/classes/GE_PaymentServices.cls
  src/classes/GE_PaymentServices_TEST.cls
  src/classes/PS_CommitmentRequest_TEST.cls
  src/classes/PS_IntegrationServiceConfig_TEST.cls
  src/classes/PS_Request.cls
  src/classes/PS_Request_TEST.cls
  src/classes/RD2_EntryFormController_TEST.cls
  src/classes/UTIL_AuraEnabledCommon.cls
  src/classes/UTIL_Http.cls
  src/classes/UTIL_Http_TEST.cls
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
  src/lwc/psElevateTokenHandler/psElevateTokenHandler.js
  src/lwc/rd2ElevateCreditCardForm/rd2ElevateCreditCardForm.js
  src/pages/GE_TokenizeCard.page
  unpackaged/config/ps_testing/classes/PS_TestPaymentService.cls
Labels: Not-to-master, QE - Test

#5895 Adoption: Create Resource Component to Adoption page
  src/labels/CustomLabels.labels
  src/lwc/gsResources/gsResources.css
  src/lwc/gsResources/gsResources.html
  src/lwc/gsResources/gsResources.js
  src/lwc/gsResources/gsResources.js-meta.xml
  src/package.xml
Labels: Nonprofit-Optimize, Not-to-master, QE - Test
