Repository SalesforceFoundation/NPSP, pull requests merged in 2020-01, with the labels that each got.

#4921 NPSP DevOrg Test Data Tweaks
  cumulusci.yml
  datasets/dev_org/test_data.sql
  datasets/mapping.yml
  datasets/mapping_managed.yml
Labels: Infrastructure

#4904 Gift Entry: Fix issues from Custom Labels WI QA
  src/lwc/geTemplateBuilder/geTemplateBuilder.js
Labels: Not-to-master

#4879 CCI Task to cleanup translation metadata after using retrieve_unpackaged task
  cumulusci.yml
Labels: Infrastructure

#4925 TestData1K: Correct 1K test data sql to match updated mapping file
  datasets/1k/test_data.sql
Labels: Infrastructure

#4915 Updated TSO id to NPSP 3.167
  orgs/trial.json
Labels: Infrastructure

#4917 [W-038348] Refactoring Manage Household Robot tests to Page Object Pattern
  robot/Cumulus/resources/ManageHouseHoldPageObject.py
  robot/Cumulus/resources/NPSP.py
  robot/Cumulus/resources/locators_47.py
  robot/Cumulus/tests/browser/manage_households/add_address_managehh.robot
  robot/Cumulus/tests/browser/manage_households/add_existingcontact_managehh.robot
  robot/Cumulus/tests/browser/manage_households/add_newcontact_managehh.robot
  robot/Cumulus/tests/browser/manage_households/change_naming_managehh.robot
Labels: Test Automation

#4916 RD2: Enhanced Recurring Donations label updates
  src/aura/RD2_EnablementDelegate/RD2_EnablementDelegate.cmp
  src/labels/CustomLabels.labels
  src/objects/RecurringDonationSchedule__c.object
  src/objects/npe03__Recurring_Donation__c.object
Labels: Not-to-master

#4914 Gift Entry: Error Message feature when advanced mapping is disabled
  src/lwc/geTemplates/geTemplates.html
  src/lwc/geTemplates/geTemplates.js
Labels: Not-to-master

#4919 Gift Entry: enforce unique form template names in builder
  src/classes/FORM_ServiceGiftEntry.cls
  src/classes/FORM_ServiceGiftEntry_TEST.cls
  src/classes/FORM_ServiceGiftEntry_TEST.cls-meta.xml
  src/classes/GE_FormRendererService_TEST.cls
  src/lwc/geTemplateBuilder/geTemplateBuilder.html
  src/lwc/geTemplateBuilder/geTemplateBuilder.js
  src/lwc/geTemplateBuilderTemplateInfo/geTemplateBuilderTemplateInfo.html
  src/lwc/geTemplateBuilderTemplateInfo/geTemplateBuilderTemplateInfo.js
  src/package.xml
Labels: Not-to-master

#4905 Gift Entry: Update template list view and add batch list view
  src/aura/GE_GiftEntry/GE_GiftEntry.cmp
  src/aura/GE_GiftEntry/GE_GiftEntry.cmp-meta.xml
  src/aura/GE_GiftEntry/GE_GiftEntry.css
  src/aura/GE_GiftEntry/GE_GiftEntryController.js
  src/classes/FORM_ServiceGiftEntry.cls
  src/classes/FORM_ServiceGiftEntry_TEST.cls
  src/labels/CustomLabels.labels
  src/lwc/geLabelService/geLabelService.js
  src/lwc/geListView/geListView.css
  src/lwc/geListView/geListView.html
  src/lwc/geListView/geListView.js
  src/lwc/geListView/geListView.js-meta.xml
  src/lwc/geTemplateBuilderService/geTemplateBuilderService.js
  src/lwc/geTemplates/geTemplates.css
  src/lwc/geTemplates/geTemplates.html
  src/lwc/geTemplates/geTemplates.js
  src/lwc/libsMoment/libsMoment.js
  src/lwc/libsMoment/libsMoment.js-meta.xml
  src/lwc/utilDualListbox/utilDualListbox.html
  src/lwc/utilDualListbox/utilDualListbox.js
  src/lwc/utilDualListbox/utilDualListbox.js-meta.xml
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
  src/objects/Custom_Column_Header__c.object
  src/objects/Form_Template__c.object
  src/package.xml
  src/tabs/GE_Templates.tab
Labels: Not-to-master

#4948 Gift Entry: Fix hardcoded values in batches list view
  src/labels/CustomLabels.labels
  src/lwc/geLabelService/geLabelService.js
  src/lwc/geTemplates/geTemplates.html
  src/lwc/geTemplates/geTemplates.js
  src/package.xml
Labels: Not-to-master

#4941 RD2: Create next Opportunity for RD having Closed Lost Opp in migration
  src/classes/RD2_DataMigrationBase_BATCH.cls
  src/classes/RD2_DataMigration_TEST.cls
  src/classes/RD2_OpportunityEvaluation_TEST.cls
  src/classes/RD2_OpportunityService.cls
  src/classes/TEST_SObjectGateway.cls
Labels: Not-to-master

#4938 Gift Entry: Added validation on template save
  src/labels/CustomLabels.labels
  src/lwc/geLabelService/geLabelService.js
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.html
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.js
  src/package.xml
Labels: Not-to-master

#4926 RD2: Display Active Schedule on the RD Lightning Page
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/classes/RD2_VisualizeScheduleController.cls
  src/classes/RD2_VisualizeScheduleController_TEST.cls
  src/classes/RD2_VisualizeScheduleController_TEST.cls-meta.xml
  src/labels/CustomLabels.labels
  src/lwc/jsconfig.json
  src/lwc/rdActiveSchedule/rdActiveSchedule.html
  src/lwc/rdActiveSchedule/rdActiveSchedule.js
  src/lwc/rdActiveSchedule/rdActiveSchedule.js-meta.xml
  src/lwc/rdScheduleVisualizer/rdScheduleVisualizer.css
  src/lwc/rdScheduleVisualizer/rdScheduleVisualizer.html
  src/lwc/rdScheduleVisualizer/rdScheduleVisualizer.js
  src/lwc/rdScheduleVisualizer/rdScheduleVisualizer.js-meta.xml
  src/package.xml
Labels: Not-to-master, QE - Test

#4962 Gift Entry: Fix an import
  src/lwc/geListView/geListView.js
  src/lwc/geTemplates/geTemplates.js
Labels: Not-to-master

#4958 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Infrastructure

#4954 Updating TSO ID to 3.168
  orgs/trial.json
Labels: Infrastructure

#4959 Gift Entry: Add data import batch wizard
  src/aura/GE_GiftEntry/GE_GiftEntry.cmp
  src/aura/GE_GiftEntry/GE_GiftEntry.css
  src/aura/GE_GiftEntry/GE_GiftEntryController.js
  src/classes/FORM_Element.cls
  src/classes/FORM_ServiceGiftEntry.cls
  src/labels/CustomLabels.labels
  src/lwc/geBatchWizard/geBatchWizard.css
  src/lwc/geBatchWizard/geBatchWizard.html
  src/lwc/geBatchWizard/geBatchWizard.js
  src/lwc/geBatchWizard/geBatchWizard.js-meta.xml
  src/lwc/geLabelService/geLabelService.js
  src/lwc/geListView/geListView.js
  src/lwc/geTemplateBuilder/geTemplateBuilder.html
  src/lwc/geTemplateBuilder/geTemplateBuilder.js
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.html
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.js
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.js
  src/lwc/geTemplates/geTemplates.html
  src/lwc/geTemplates/geTemplates.js
  src/lwc/utilCommon/utilCommon.js
  src/lwc/utilExpandableSection/utilExpandableSection.css
  src/lwc/utilExpandableSection/utilExpandableSection.html
  src/lwc/utilExpandableSection/utilExpandableSection.js
  src/lwc/utilExpandableSection/utilExpandableSection.js-meta.xml
  src/lwc/utilInput/utilInput.html
  src/lwc/utilInput/utilInput.js
  src/lwc/utilInput/utilInput.js-meta.xml
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
  src/objects/DataImportBatch__c.object
  src/package.xml
Labels: Not-to-master

#4970 Gift Entry: use custom lookup component in template builder and batch wizard
  src/lwc/geAutocomplete/geAutocomplete.css
  src/lwc/geAutocomplete/geAutocomplete.js
  src/lwc/geFormFieldLookup/geFormFieldLookup.html
  src/lwc/geFormFieldLookup/geFormFieldLookup.js
  src/lwc/utilInput/utilInput.html
  src/lwc/utilInput/utilInput.js
Labels: Not-to-master

#4967 Gift Entry: Change form template clone action
  src/classes/FORM_Service.cls
  src/classes/FORM_ServiceGiftEntry.cls
  src/classes/FORM_ServiceGiftEntry_TEST.cls
  src/lwc/geTemplateBuilder/geTemplateBuilder.js
  src/lwc/geTemplates/geTemplates.js
Labels: Not-to-master

#4972 Use custom labels always, fix SGE loading
  src/lwc/geFormField/geFormField.html
  src/lwc/geFormField/geFormField.js
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
Labels: Not-to-master

#4957 RD2: Consider future Closed Won/Lost Opps when matching projected installments
  src/classes/RD2_OpportunityEvaluationService_TEST.cls
  src/classes/RD2_OpportunityService.cls
Labels: Not-to-master

#4982 Gift Entry: one gift entry tab.
  src/aura/GE_GiftEntry/GE_GiftEntry.cmp
  src/aura/GE_GiftEntry/GE_GiftEntryController.js
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geHome/geHome.css
  src/lwc/geHome/geHome.html
  src/lwc/geHome/geHome.js
  src/lwc/geHome/geHome.js-meta.xml
  src/lwc/geListView/geListView.js
  src/lwc/geTemplateBuilder/geTemplateBuilder.html
  src/lwc/geTemplateBuilder/geTemplateBuilder.js
  src/lwc/geTemplateBuilderFormSection/geTemplateBuilderFormSection.js
  src/lwc/geTemplateBuilderSectionModalBody/geTemplateBuilderSectionModalBody.js
  src/lwc/geTemplates/geTemplates.js
  src/lwc/utilDualListbox/utilDualListbox.js
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
  src/objects/Account.object
  src/objects/Contact.object
  src/package.xml
  src/tabs/GE_Form_Renderer.tab
  src/tabs/GE_Gift_Entry.tab
  src/tabs/GE_Template_Builder.tab
  unpackaged/config/dev/profiles/Admin.profile
Labels: Not-to-master

#4984 Gift Entry: Fix value check
  src/lwc/utilInput/utilInput.js
Labels: Not-to-master

#4988 Gift Entry: track properties
  src/lwc/geHome/geHome.js
Labels: Not-to-master

#4975 Add namespaced prerelease org
  cumulusci.yml
Labels: Infrastructure

#4983 Gift Entry: Feature Gating GE
  src/classes/UTIL_CustomSettingsFacade.cls
  src/labels/CustomLabels.labels
  src/lwc/geFormRenderer/geFormRenderer.html
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geTemplateBuilder/geTemplateBuilder.js
  src/lwc/geTemplates/geTemplates.js
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
  src/objects/Gift_Entry_Settings__c.object
  src/package.xml
Labels: Not-to-master

#4973 RD2: Do Not Reset Effective Date to Current Date
  src/classes/RD2_RecurringDonations_TEST.cls
  src/classes/RD2_ScheduleService.cls
  src/classes/RD2_ScheduleService_TEST.cls
  src/lwc/rdActiveSchedule/rdActiveSchedule.html
Labels: Not-to-master

#4918 RD2: Configure Installment Auto Creation
  src/classes/RD2_Constants.cls
  src/classes/RD2_OpportunityEvaluationService.cls
  src/classes/RD2_OpportunityEvaluationService_TEST.cls
  src/classes/RD2_OpportunityEvaluation_TEST.cls
  src/classes/RD2_Settings.cls
  src/classes/RD2_Settings_TEST.cls
  src/classes/STG_PanelRD_CTRL.cls
  src/classes/STG_SettingsManager_TEST.cls
  src/classes/UTIL_CustomSettingsFacade.cls
  src/labels/CustomLabels.labels
  src/objects/npe03__Recurring_Donations_Settings__c.object
  src/package.xml
  src/pages/STG_PanelRD.page
Labels: Not-to-master

#5005 Gift Entry: fix issues
  src/lwc/geListView/geListView.js
Labels: Not-to-master

#5014 import allocation and allocation settings fields
  src/lwc/geFormWidgetAllocation/geFormWidgetAllocation.js
  src/lwc/geFormWidgetRow/geFormWidgetRow.js
Labels: Not-to-master

#4998 Gift Entry: Add donation matching modal
  src/labels/CustomLabels.labels
  src/lwc/geDonationMatching/geDonationMatching.html
  src/lwc/geDonationMatching/geDonationMatching.js
  src/lwc/geDonationMatching/geDonationMatching.js-meta.xml
  src/lwc/geDonationMatchingOpportunityCard/geDonationMatchingOpportunityCard.css
  src/lwc/geDonationMatchingOpportunityCard/geDonationMatchingOpportunityCard.html
  src/lwc/geDonationMatchingOpportunityCard/geDonationMatchingOpportunityCard.js
  src/lwc/geDonationMatchingOpportunityCard/geDonationMatchingOpportunityCard.js-meta.xml
  src/lwc/geDonationMatchingPaymentCard/geDonationMatchingPaymentCard.css
  src/lwc/geDonationMatchingPaymentCard/geDonationMatchingPaymentCard.html
  src/lwc/geDonationMatchingPaymentCard/geDonationMatchingPaymentCard.js
  src/lwc/geDonationMatchingPaymentCard/geDonationMatchingPaymentCard.js-meta.xml
  src/lwc/geLabelService/geLabelService.js
  src/lwc/geReviewDonations/geReviewDonations.css
  src/lwc/geReviewDonations/geReviewDonations.html
  src/lwc/geReviewDonations/geReviewDonations.js
  src/lwc/geReviewDonations/geReviewDonations.js-meta.xml
  src/lwc/utilCard/utilCard.html
  src/lwc/utilCard/utilCard.js
  src/lwc/utilCard/utilCard.js-meta.xml
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
  src/package.xml
Labels: Not-to-master

#5010 Gift Entry: Feature Gate UI
  src/classes/STG_PanelDataImportAdvancedMapping_CTRL.cls
  src/labels/CustomLabels.labels
  src/package.xml
  src/pages/STG_PanelDataImportAdvancedMapping.page
Labels: Not-to-master

#5016 Psadie/gau widget definition
  src/classes/BDI_FieldMapping.cls
  src/classes/FORM_Element.cls
  src/lwc/geFormWidgetAllocation/geFormWidgetAllocation.js
  src/lwc/geTemplateBuilder/geTemplateBuilder.js
  src/lwc/geTemplateBuilderService/geTemplateBuilderService.js
  src/lwc/geWidgetService/geWidgetService.js
  src/lwc/geWidgetService/geWidgetService.js-meta.xml
  src/lwc/utilCommon/utilCommon.js
Labels: Not-to-master

#5020 Gift Entry: Wire up review donations button
  src/aura/GE_GiftEntry/GE_GiftEntryController.js
  src/aura/GE_GiftEntry/GE_GiftEntryHelper.js
  src/aura/GE_GiftEntryForm/GE_GiftEntryForm.cmp
  src/aura/GE_GiftEntryForm/GE_GiftEntryFormController.js
  src/classes/GE_FormRendererService.cls
  src/classes/GE_FormRendererService_TEST.cls
  src/lwc/geDonationMatching/geDonationMatching.html
  src/lwc/geDonationMatchingOpportunityCard/geDonationMatchingOpportunityCard.html
  src/lwc/geDonationMatchingOpportunityCard/geDonationMatchingOpportunityCard.js
  src/lwc/geDonationMatchingPaymentCard/geDonationMatchingPaymentCard.html
  src/lwc/geFormField/geFormField.js
  src/lwc/geFormRenderer/geFormRenderer.html
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geFormSection/geFormSection.html
  src/lwc/geFormSection/geFormSection.js
  src/lwc/geFormService/geFormService.js
  src/lwc/geGiftEntryFormApp/geGiftEntryFormApp.html
  src/lwc/geGiftEntryFormApp/geGiftEntryFormApp.js
  src/lwc/geHome/geHome.html
  src/lwc/geHome/geHome.js
  src/lwc/geReviewDonations/geReviewDonations.js
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
Labels: Not-to-master

#5015 Updating TSO ID to 3.169
  orgs/trial.json
Labels: Infrastructure

#5034 fix widget service
  src/lwc/geFormWidgetAllocation/geFormWidgetAllocation.js
  src/lwc/geWidgetService/geWidgetService.js
Labels: Not-to-master

#5007 Gift Entry: Added page access and feature gate check to geHome
  src/lwc/geFormRenderer/geFormRenderer.html
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geHome/geHome.html
  src/lwc/geHome/geHome.js
  src/lwc/geTemplateBuilder/geTemplateBuilder.html
  src/lwc/geTemplateBuilder/geTemplateBuilder.js
  src/lwc/geTemplates/geTemplates.html
  src/lwc/geTemplates/geTemplates.js
Labels: Not-to-master

#5027 Gift Entry: Fix list view default order by error
  src/lwc/geListView/geListView.js
Labels: Not-to-master

#5035 Gift Entry: template builder ui updates
  src/lwc/geTemplateBuilder/geTemplateBuilder.css
  src/lwc/geTemplateBuilder/geTemplateBuilder.html
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.html
Labels: Not-to-master

#4992 RD2: Contact and Account Update Behavior
  src/classes/RD2_OpportunityService.cls
  src/classes/RD2_OpportunityService_TEST.cls
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/RD2_ValidationService.cls
  src/classes/RD2_ValidationService_TEST.cls
  src/classes/UTIL_SObject.cls
  src/classes/UTIL_SObject_TEST.cls
  src/classes/UTIL_UnitTestData_TEST.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master
