Repository SalesforceFoundation/NPSP, pull requests merged in 2020-03, with the labels that each got.

#5225 CCI: New Flow to create a testing user, enable LoginAs by default in scratch orgs
  cumulusci.yml
  lib/npsp_standard_user_profile.xml
  orgs/beta.json
  orgs/dev.json
  orgs/feature.json
  scripts/New_Testing_User.cls
  src/pages/LVL_LevelEdit.page
  unpackaged/config/npsp_standard_user_profile/package.xml
  unpackaged/config/npsp_standard_user_profile/profiles/NPSP_Standard_User.profile
Labels: Infrastructure

#5203 Gift Entry: add tokenize widget stub
  src/labels/CustomLabels.labels
  src/lwc/geFormWidget/geFormWidget.html
  src/lwc/geFormWidget/geFormWidget.js
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.css
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.html
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js-meta.xml
  src/lwc/geLabelService/geLabelService.js
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.css
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.html
  src/lwc/geTemplateBuilderFormField/geTemplateBuilderFormField.js
  src/lwc/geTemplateBuilderService/geTemplateBuilderService.js
  src/lwc/geTemplateBuilderWidget/geTemplateBuilderWidget.css
  src/lwc/geTemplateBuilderWidget/geTemplateBuilderWidget.html
  src/lwc/geTemplateBuilderWidget/geTemplateBuilderWidget.js
  src/lwc/geTemplateBuilderWidget/geTemplateBuilderWidget.js-meta.xml
  src/lwc/geWidgetService/geWidgetService.js
  src/lwc/geWidgetService/widgetStubs.js
  src/lwc/utilInput/utilInput.html
  src/lwc/utilInput/utilInput.js
  src/package.xml
Labels: Not-to-master

#5210 CCI: Enable Automatic RD Naming in the npsp_default_settings cci task.
  scripts/configure_npsp_default_settings.cls
Labels: Infrastructure

#5239 CCI: Flow to fully configure and enable RD2 in a scratch org
  cumulusci.yml
Labels: Infrastructure

#5207 Gift Entry: add elevate iframe
  src/classes/GE_GiftEntryController.cls
  src/classes/GE_PaymentServices.cls
  src/classes/GE_PaymentServices.cls-meta.xml
  src/classes/GE_PaymentServices_TEST.cls
  src/classes/GE_PaymentServices_TEST.cls-meta.xml
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.css
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.html
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.html
  src/package.xml
  src/pages/GE_TokenizeCard.page
  src/pages/GE_TokenizeCard.page-meta.xml
Labels: Not-to-master

#5253 [Robot] Recurring donations page object changes
  robot/Cumulus/resources/NPSP.py
  robot/Cumulus/resources/NPSPSettingsPageObject.py
  robot/Cumulus/tests/browser/recurring_donations/check_recurring_auto_naming.robot
  robot/Cumulus/tests/browser/recurring_donations/create_a_fixed_length_recurring_donation_divide_by.robot
  robot/Cumulus/tests/browser/recurring_donations/create_a_fixed_length_recurring_donation_multiply_by.robot
  robot/Cumulus/tests/browser/recurring_donations/create_and_close_recurring_donation_and_refresh_opportunities.robot
  robot/Cumulus/tests/browser/recurring_donations/create_recurring_donation_and_check_rollups.robot
  robot/Cumulus/tests/browser/recurring_donations/create_recurring_donation_ui.robot
Labels: Test Automation

#5166 Translate Gender__c field in Trial org configuration
  unpackaged/config/trial_translations/objectTranslations/Contact-de.objectTranslation
  unpackaged/config/trial_translations/objectTranslations/Contact-es.objectTranslation
  unpackaged/config/trial_translations/objectTranslations/Contact-fr.objectTranslation
  unpackaged/config/trial_translations/objectTranslations/Contact-ja.objectTranslation
  unpackaged/config/trial_translations/objectTranslations/Contact-nl_NL.objectTranslation
  unpackaged/config/trial_translations/package.xml
Labels: WIP

#5231 Gift Entry: Fabricate CardHolder Name
  src/lwc/geFormField/geFormField.js
  src/lwc/geFormFieldLookup/geFormFieldLookup.js
  src/lwc/geFormRenderer/geFormRenderer.html
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geFormSection/geFormSection.html
  src/lwc/geFormSection/geFormSection.js
  src/lwc/geFormWidget/geFormWidget.js
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
Labels: Not-to-master

#5264 [Robot] Convert GAU to use POM
  robot/Cumulus/resources/GAUPageObject.py
  robot/Cumulus/resources/NPSP.py
  robot/Cumulus/resources/NPSP.robot
  robot/Cumulus/tests/browser/gaus/assign_gau_to_opportunity.robot
  robot/Cumulus/tests/browser/gaus/create_gau.robot
Labels: Test Automation

#5267 Feature/robot pmtalloc pom
  robot/Cumulus/resources/GAUPageObject.py
  robot/Cumulus/resources/NPSP.py
  robot/Cumulus/resources/PaymentPageObject.py
  robot/Cumulus/tests/browser/gaus/assign_gau_to_opportunity.robot
  robot/Cumulus/tests/browser/zpayment_allocations/enable_pmt_alloc_and_test.robot
Labels: WIP

#5257 Gift Entry: Initial Commit for creating JWTs programmatically
  src/classes/UTIL_Jwt.cls
  src/classes/UTIL_Jwt.cls-meta.xml
  src/classes/UTIL_Jwt_TEST.cls
  src/classes/UTIL_Jwt_TEST.cls-meta.xml
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master

#5263 [Bug Bounty] Read only user can create Address records
  src/classes/ADDR_CopyAddrHHObjBTN_CTRL.cls
  src/classes/ADDR_CopyAddrHHObjBTN_TEST.cls
  src/classes/UTIL_Permissions.cls
  src/labels/CustomLabels.labels
Labels: QE - Test

#5232 Updates to automation doc to reflect recent CCI task/flow changes
  documentation/automation.md
Labels: Infrastructure

#5272 Unauthorized user can view
  src/classes/CON_DeleteContactOverride_CTRL.cls
  src/classes/PMT_PaymentWizard_CTRL.cls
  src/classes/PSC_ManageSoftCredits_CTRL.cls
  src/labels/CustomLabels.labels
  src/package.xml
  src/pages/CON_DeleteContactOverride.page
Labels: QE - Test

#5289 [Robot] Fix for the failing test under donations_payments
  robot/Cumulus/resources/NPSP.py
  robot/Cumulus/tests/browser/donations_payments/create_donation_and_payment.robot
Labels: WIP
