Repository SalesforceFoundation/NPSP, pull requests merged in 2020-09, with the labels that each got.

#5802 Recurring Donations Batch: Query AsyncApexJob without error
  src/classes/RD_RecurringDonations_TEST2.cls
  src/classes/UTIL_BatchJobService.cls
Labels: QE - Test

#5803 RD2: Disable First Installment When Field Checked
  src/classes/RD2_OpportunityEvaluationService.cls
  src/classes/RD2_OpportunityEvaluationService_TEST.cls
  src/classes/RD2_RecurringDonation.cls
  src/classes/TEST_RecurringDonationBuilder.cls
  src/classes/TEST_SObjectGateway.cls
  src/objects/npe03__Recurring_Donation__c.object
  src/package.xml
  unpackaged/config/rd2_post_config/profiles/Admin.profile
  unpackaged/config/rd2_post_config/profiles/Standard.profile
Labels: QE - Test

#5816 Support Address Platform Encryption
  src/classes/ACCT_AccountMerge_TEST.cls
  src/classes/ACCT_IndividualAccounts_TEST.cls
  src/classes/ADDR_Addresses_TEST.cls
  src/classes/ADDR_Validator_Batch.cls
  src/classes/CONV_Account_Conversion_BATCH_TEST.cls
  src/classes/GE_LookupController_TEST.cls
  src/classes/TDTM_DMLgt200_TEST.cls
  src/objects/Address__c.object
  unpackaged/config/platformencryption_fields/objects/Address__c.object
  unpackaged/config/platformencryption_fields/package.xml
Labels: QE - Test

#5833 Advanced Mapping: Bug fix for error on object group creation
  src/classes/BDI_ManageAdvancedMappingCtrl.cls
  src/lwc/bdiFieldMappings/bdiFieldMappings.js
Labels: bug

#5814 W-8017430 - P1 Bug - npsp__PaymentImportStatus set to Created even when errors
  src/classes/BDI_Donations.cls
Labels: Do Not Merge

#5857 [CCI] Rewrite npsp_default_settings task to work in a managed org
  scripts/configure_npsp_default_settings.cls
Labels: Infrastructure

#5861 [Robot] BGE fixes
  robot/Cumulus/resources/ManageHouseHoldPageObject.py
  robot/Cumulus/resources/NPSP.py
  robot/Cumulus/tests/browser/1_batch_gift_entry/bdi_batch_with_custom_fields.robot
  robot/Cumulus/tests/browser/1_batch_gift_entry/bge_default_batch_with_custom_fields.robot
  robot/Cumulus/tests/browser/manage_households/add_existingcontact_managehh.robot
  robot/Cumulus/tests/browser/manage_households/add_newcontact_managehh.robot
  robot/Cumulus/tests/browser/manage_households/change_naming_managehh.robot
Labels: WIP

#5848 RD2: Cancel Elevate Commitment
  src/classes/PS_IntegrationServiceConfig.cls
  src/classes/PS_IntegrationServiceConfig_TEST.cls
  src/classes/PS_Request.cls
  src/classes/PS_Request.cls-meta.xml
  src/classes/PS_Request_TEST.cls
  src/classes/PS_Request_TEST.cls-meta.xml
  src/classes/RD2_ElevateIntegrationService.cls
  src/classes/RD2_ElevateIntegrationService_TEST.cls
  src/classes/RD2_QueueableService.cls
  src/classes/RD2_RecurringDonations_TDTM.cls
  src/classes/RD2_RecurringDonations_TEST.cls
  src/classes/RD2_ValidationService.cls
  src/classes/RD2_ValidationService_TEST.cls
  src/classes/TDTM_ProcessControl.cls
  src/classes/UTIL_Http.cls
  src/classes/UTIL_Http.cls-meta.xml
  src/classes/UTIL_Http_TEST.cls
  src/classes/UTIL_Http_TEST.cls-meta.xml
  src/labels/CustomLabels.labels
  src/package.xml
Labels: Not-to-master

#5852 RD2: Create Elevate Commitment
  src/aura/RD2_EntryForm/RD2_EntryForm.cmp
  src/classes/PS_CommitmentRequest.cls
  src/classes/PS_CommitmentRequest.cls-meta.xml
  src/classes/PS_CommitmentRequest_TEST.cls
  src/classes/PS_CommitmentRequest_TEST.cls-meta.xml
  src/classes/PS_ElevateService.cls
  src/classes/PS_IntegrationServiceConfig.cls
  src/classes/PS_IntegrationServiceConfig_TEST.cls
  src/classes/PS_Request.cls
  src/classes/PS_Request.cls-meta.xml
  src/classes/PS_Request_TEST.cls
  src/classes/PS_Request_TEST.cls-meta.xml
  src/classes/RD2_EntryFormController.cls
  src/classes/RD2_EntryFormController_TEST.cls
  src/classes/RD2_ScheduleService.cls
  src/classes/UTIL_AuraEnabledCommon.cls
  src/classes/UTIL_Http.cls
  src/classes/UTIL_Http.cls-meta.xml
  src/classes/UTIL_Http_TEST.cls
  src/classes/UTIL_Http_TEST.cls-meta.xml
  src/labels/CustomLabels.labels
  src/lwc/rd2ElevateCreditCardForm/rd2ElevateCreditCardForm.js
  src/lwc/rd2EntryForm/rd2EntryForm.css
  src/lwc/rd2EntryForm/rd2EntryForm.html
  src/lwc/rd2EntryForm/rd2EntryForm.js
  src/package.xml
Labels: Not-to-master

#5853 RD2: Support Cardholder Name in the Credit Card widget
  src/labels/CustomLabels.labels
  src/lwc/psElevateTokenHandler/psElevateTokenHandler.js
  src/lwc/rd2ElevateCreditCardForm/rd2ElevateCreditCardForm.css
  src/lwc/rd2ElevateCreditCardForm/rd2ElevateCreditCardForm.html
  src/lwc/rd2ElevateCreditCardForm/rd2ElevateCreditCardForm.js
  src/lwc/rd2EntryForm/rd2EntryForm.js
  src/package.xml
  src/pages/GE_TokenizeCard.page
Labels: Not-to-master

#5862 RD2: Prevent Elevate credit card widget display
  src/lwc/rd2EntryForm/rd2EntryForm.html
  src/lwc/rd2EntryForm/rd2EntryForm.js
  src/lwc/rd2EntryFormDonorSection/rd2EntryFormDonorSection.html
  src/lwc/rd2EntryFormDonorSection/rd2EntryFormDonorSection.js
  src/lwc/rd2EntryFormScheduleSection/rd2EntryFormScheduleSection.html
  src/lwc/rd2EntryFormScheduleSection/rd2EntryFormScheduleSection.js
  src/package.xml
Labels: Not-to-master

#5885 [CCI] NPSP Default Settings Task: Pre-configure Allocation and Affiliation settings
  scripts/configure_npsp_default_settings.cls
Labels: Infrastructure
