Repository SalesforceFoundation/NPSP, pull requests merged in 2021-03, with the labels that each got.

#6273 Hide unneccessary checkbox column from BGE table
  src/lwc/geBatchGiftEntryTable/geBatchGiftEntryTable.html
Labels: cla:missing, cla:missing

#6245 Fix Merge Accounts SELF_REFERENCE_FROM_TRIGGER Error
  src/classes/ACCT_AccountMerge_TDTM.cls
Labels: QE - Test

#6271 Better Multi-currency support in Batch Gift Entry
  src/classes/BGE_DataImportBatchEntry_CTRL.cls
  src/classes/BGE_DataImportBatchEntry_CTRL_TEST.cls
  src/classes/GE_GiftEntryController.cls
  src/classes/GE_GiftEntryController_TEST.cls
  src/labels/CustomLabels.labels
  src/lwc/geBatchGiftEntryTable/geBatchGiftEntryTable.html
  src/lwc/geBatchGiftEntryTable/geBatchGiftEntryTable.js
  src/lwc/geBatchWizard/geBatchWizard.js
  src/lwc/geFormRenderer/exceptionDataError.js
  src/lwc/geFormRenderer/geFormRenderer.css
  src/lwc/geFormRenderer/geFormRenderer.html
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geGiftEntryFormApp/geGiftEntryFormApp.html
  src/lwc/geGiftEntryFormApp/geGiftEntryFormApp.js
  src/lwc/geLabelService/geLabelService.js
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.js
  src/lwc/utilProgressBar/utilProgressBar.html
  src/lwc/utilTemplateBuilder/utilTemplateBuilder.js
  src/package.xml
Labels: bug

#6270 Enhanced Recurring Donations Nightly Batch Job performance test flow
  cumulusci.yml
  robot/Cumulus/perftests/RD_Batch_Tests.robot
  robot/Cumulus/perftests/Readme_Persistent_SandboxOrg.md
Labels: Infrastructure

#6307 Require Opportunity Amount Access for Payment Wizard
  src/classes/PMT_PaymentWizard_CTRL.cls
  src/classes/PMT_PaymentWizard_TEST.cls
  src/pages/PMT_PaymentWizard.page
Labels: bug
