Repository SalesforceFoundation/NPSP, pull requests merged in 2021-09, with the labels that each got.

#6649 Update TSO
  orgs/trial.json
Labels: ready for RE review

#6644 [Gift Entry] Soft Credits deduplication
  force-app/main/default/classes/Donation.cls
  force-app/main/default/classes/Donation_TEST.cls
  force-app/main/default/classes/Gift.cls
  force-app/main/default/classes/Gift_Test.cls
  force-app/main/default/classes/SoftCredit.cls
  force-app/main/default/classes/SoftCredit.cls-meta.xml
  force-app/main/default/classes/SoftCredit_TEST.cls
  force-app/main/default/classes/SoftCredit_TEST.cls-meta.xml
  force-app/main/default/classes/SoftCredits.cls
  force-app/main/default/classes/SoftCredits_TEST.cls
  force-app/main/default/classes/UTIL_AdditionalObjectData_TEST.cls
  force-app/main/default/lwc/geFormWidgetSoftCreditRow/geFormWidgetSoftCreditRow.html
  force-app/main/default/lwc/geFormWidgetSoftCreditRow/geFormWidgetSoftCreditRow.js
  force-app/main/default/lwc/geGift/__tests__/geGift.test.js
  force-app/main/default/lwc/geGift/geGift.js
  force-app/main/default/lwc/geGift/geSoftCredits.js
Labels: Not-to-master

#6648 Ensure Contact Merge page behavior is as expected
  force-app/main/adapter/in/sobjects/contact/Contacts.cls
  force-app/main/default/classes/CON_ContactMerge_CTRL.cls
  force-app/main/default/classes/NPSP_Address.cls
  force-app/test/ADDR_Contacts_TEST.cls
Labels: Do Not Merge

#6651 W-8256939 - Payment Allocations - Recurring Donations Updates to Allocation not Propagating to Payment Allocations for Open Opportunities
  force-app/main/default/classes/ALLO_Allocations_TDTM.cls
  force-app/main/default/classes/ALLO_Allocations_TEST.cls
Labels: WIP

#6631 Refactor the BDI Performance Tests
  cumulusci.yml
  datasets/bdi_benchmark/BDI-With-Matching.recipe.yml
  datasets/bdi_benchmark/BDI-Without-Matching.recipe.yml
  datasets/bdi_benchmark/BDI.recipe.yml
  robot/Cumulus/perftests/BDI_Tests.robot
  robot/Cumulus/resources/BDI_API.robot
Labels: Infrastructure, ready for RE review

#6661 [Gift Entry] Soft Credits component performance improvements
  force-app/main/default/lwc/geBatchGiftEntryHeader/__tests__/geBatchGiftEntryHeader.test.js
  force-app/main/default/lwc/geBatchGiftEntryHeader/geBatchGiftEntryHeader.html
  force-app/main/default/lwc/geBatchGiftEntryHeader/geBatchGiftEntryHeader.js
  force-app/main/default/lwc/geFormRenderer/geFormRenderer.js
  force-app/main/default/lwc/geFormWidget/geFormWidget.html
  force-app/main/default/lwc/geFormWidgetSoftCredit/__tests__/geFormWidgetSoftCredit.test.js
  force-app/main/default/lwc/geFormWidgetSoftCredit/geFormWidgetSoftCredit.html
  force-app/main/default/lwc/geFormWidgetSoftCredit/geFormWidgetSoftCredit.js
  force-app/main/default/lwc/geGift/__tests__/geGift.test.js
  force-app/main/default/lwc/geGift/geGift.js
  force-app/main/default/lwc/geGift/geSoftCredits.js
  force-app/main/default/lwc/geGiftEntryFormApp/__tests__/geGiftEntryFormApp.test.js
  force-app/main/default/lwc/geGiftEntryFormApp/geGiftEntryFormApp.html
  force-app/main/default/lwc/geGiftEntryFormApp/geGiftEntryFormApp.js
Labels: Not-to-master, cla:missing

#6665 Fix for Client Id Config Bug
  force-app/main/default/classes/GE_PaymentServices_TEST.cls
  force-app/main/default/classes/PS_GatewayManagement_TEST.cls
  force-app/main/default/classes/PS_IntegrationServiceConfig.cls
  force-app/main/default/classes/PS_IntegrationServiceConfig_TEST.cls
  force-app/main/default/classes/PaymentServicesConfigurationSelector.cls
  force-app/main/default/classes/PaymentServicesConfigurationSelector.cls-meta.xml
Labels: bug
