Repository SalesforceFoundation/NPSP, pull requests merged in 2021-02, with the labels that each got.

#6214 Trigger new package version
  src/lwc/geLabelService/geLabelService.js
Labels: Not-to-master

#5762 CCI: New LDV Data Factory Recipe & Flow
  cumulusci.yml
  datasets/rd2/config_npsp_for_ldv_data_load.cls
  datasets/rd2/data.sql
  datasets/rd2/data_recipe_with_rd2.yml
  datasets/rd2/data_recipe_with_rd2_mapping.yml
  datasets/rd2/mapping_managed.yml
  datasets/rd2/opportunity_macros.yml
  datasets/rd2/readme.md
  datasets/rd2/recurring_donation_macros.yml
  datasets/rd2_pilot/rd_ldv_factory.yml
  documentation/automation.md
  robot/Cumulus/perftests/Insert_Tests.robot
  unpackaged/config/config_ldv_org_for_testing/applications/Nonprofit_Success_Pack.app
  unpackaged/config/config_ldv_org_for_testing/classes/TEMP_ClosePledgedDonations.cls
  unpackaged/config/config_ldv_org_for_testing/classes/TEMP_ClosePledgedDonations.cls-meta.xml
  unpackaged/config/config_ldv_org_for_testing/objects/___NAMESPACE___Error__c.object
  unpackaged/config/config_ldv_org_for_testing/objects/___NAMESPACE___Trigger_Handler__c.object
  unpackaged/config/config_ldv_org_for_testing/objects/npe03__Recurring_Donation__c.object
  unpackaged/config/config_ldv_org_for_testing/package.xml
  unpackaged/config/config_ldv_org_for_testing/profiles/Admin.profile
  unpackaged/config/config_ldv_org_for_testing/tabs/___NAMESPACE___Error__c.tab
  unpackaged/config/config_ldv_org_for_testing/tabs/___NAMESPACE___Trigger_Handler__c.tab
Labels: Infrastructure

#6210 Dispatch Scheduled Jobs from Apex
  src/classes/CallableApiApexDelegationService.cls
  src/classes/CallableApiApexDelegationService.cls-meta.xml
  src/classes/CallableApiApexDelegationService_TEST.cls
  src/classes/CallableApiApexDelegationService_TEST.cls-meta.xml
  src/classes/CallableApiParameters.cls
  src/classes/Callable_API.cls
  src/classes/Callable_API_TEST.cls
  src/labels/CustomLabels.labels
  src/package.xml
Labels: QE - Test, cla:signed

#6231 Set Payment_Elevate_Created_UTC_Timestamp__c field
  src/lwc/geFormRenderer/geFormRenderer.js
Labels: Not-to-master

#6242 RD: Show Card Last 4 and Expiration Date in the Elevate Information Widget
  src/classes/RD2_ElevateInformation_CTRL.cls
  src/classes/RD2_ElevateInformation_TEST.cls
  src/lwc/rd2ElevateInformation/__tests__/data/getData.json
  src/lwc/rd2ElevateInformation/__tests__/data/getObjectInfo.json
  src/lwc/rd2ElevateInformation/__tests__/data/getRecord.json
  src/lwc/rd2ElevateInformation/__tests__/rd2ElevateInformation.test.js
  src/lwc/rd2ElevateInformation/rd2ElevateInformation.html
  src/lwc/rd2ElevateInformation/rd2ElevateInformation.js
Labels: Not-to-master, QE - Test

#6248 RD: Update Credit Card Payment From Payment Information Modal
  src/classes/RD2_ElevateInformation_CTRL.cls
  src/classes/RD2_ElevateInformation_TEST.cls
  src/classes/RD2_ElevateIntegrationService.cls
  src/classes/RD2_EntryFormController.cls
  src/labels/CustomLabels.labels
  src/lwc/rd2EditPaymentInformationModal/rd2EditPaymentInformationModal.css
  src/lwc/rd2EditPaymentInformationModal/rd2EditPaymentInformationModal.html
  src/lwc/rd2EditPaymentInformationModal/rd2EditPaymentInformationModal.js
  src/lwc/rd2EditPaymentInformationModal/rd2EditPaymentInformationModal.js-meta.xml
  src/lwc/rd2ElevateCreditCardForm/rd2ElevateCreditCardForm.html
  src/lwc/rd2ElevateCreditCardForm/rd2ElevateCreditCardForm.js
  src/lwc/rd2ElevateInformation/rd2ElevateInformation.html
  src/lwc/rd2ElevateInformation/rd2ElevateInformation.js
  src/package.xml
Labels: Not-to-master
