Repository SalesforceFoundation/NPSP, pull requests merged in 2021-01, with the labels that each got.

#6149 Jest Package Dependency Update
  package.json
  yarn.lock
Labels: Infrastructure

#6154 [GS End User][W-8528117] Create Label and add the End user Resources list
  src/labels/CustomLabels.labels
  src/lwc/gsLabelMapper/gsLabelMapper.js
  src/lwc/gsResources/gsResources.js
  src/package.xml
Labels: Nonprofit-Optimize, Not-to-master

#6150 Feature/adoption trailhead component
  StaticResourceSources/gsAssets/trailheadComponent/trailheadLogo.png
  StaticResourceSources/gsAssets/trailheadComponent/trailheadLogo.svg
  src/labels/CustomLabels.labels
  src/lwc/gseuTrailhead/gseuTrailhead.css
  src/lwc/gseuTrailhead/gseuTrailhead.html
  src/lwc/gseuTrailhead/gseuTrailhead.js
  src/lwc/gseuTrailhead/gseuTrailhead.js-meta.xml
  src/package.xml
  src/staticresources/CumulusStaticResources.resource
Labels: Nonprofit-Optimize, Not-to-master

#6158 Added missing credit card constant
  src/lwc/geConstants/geConstants.js
  src/lwc/geFormRenderer/geFormRenderer.js
Labels: Not-to-master, bug

#6151 Fix Status to State Mapping page invalid Deployment Id error
  src/classes/RD2_StatusMappingSettings_CTRL.cls
  src/classes/RD2_StatusMappingSettings_TEST.cls
Labels: QE - Test

#6181 Handle failure for SGE ACH
  src/labels/CustomLabels.labels
  src/lwc/geConstants/geConstants.js
  src/lwc/geFormRenderer/geFormRenderer.js
  src/lwc/geFormWidget/geFormWidget.js
  src/lwc/geFormWidgetTokenizeCard/__tests__/geFormWidgetTokenizeCard.test.js
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.html
  src/lwc/geFormWidgetTokenizeCard/geFormWidgetTokenizeCard.js
Labels: Not-to-master

#6168 [GS End User] [W-8528035] Checklist Section 1 (Welcome)
  StaticResourceSources/gsAssets/step/What_is_Nonprofit_Cloud_modified_undraw_going_up_ttm5.svg
  StaticResourceSources/gsAssets/step/What_is_Nonprofit_Success_Pack_undraw_personal_finance_tqcd.svg
  src/customMetadata/GetStartedChecklistItem.What_is_Nonprofit_Cloud.md
  src/customMetadata/GetStartedChecklistItem.What_is_Nonprofit_Success_Pack.md
  src/customMetadata/GetStartedChecklistSection.Welcome_NPSP.md
  src/labels/CustomLabels.labels
  src/lwc/gsChecklistItem/gsChecklistItem.css
  src/lwc/gsLabelMapper/gsLabelMapper.js
  src/package.xml
  src/staticresources/CumulusStaticResources.resource
Labels: Nonprofit-Optimize, Not-to-master

#6174 Feature/adoption title
  src/flexipages/GetStarted.flexipage
  src/labels/CustomLabels.labels
  src/lwc/gsChecklistSetup/gsChecklistSetup.js
  src/lwc/gsChecklistSetup/gsChecklistSetup.js-meta.xml
  src/lwc/gsLabelMapper/gsLabelMapper.js
  src/package.xml
Labels: Nonprofit-Optimize

#6182 [W-8720206] [GS End User] Section headers are not focusable
  src/lwc/gsAccordionLabel/gsAccordionLabel.html
Labels: Nonprofit-Optimize, Not-to-master

#6173 [GS End User] [W-8545389] - Checklist Section 2 (Create Constituent Records)
  StaticResourceSources/gsAssets/step/Connect_Two_Contacts_with_Relationships.svg
  StaticResourceSources/gsAssets/step/Connect_a_Contact_to_an_Organization_with_Affiliations.svg
  StaticResourceSources/gsAssets/step/Create_Contacts_With_Household_Accounts.svg
  src/customMetadata/GetStartedChecklistItem.Connect_Two_Contacts_with_Relationships.md
  src/customMetadata/GetStartedChecklistItem.Connect_a_Contact_to_an_Organization.md
  src/customMetadata/GetStartedChecklistItem.Create_Contacts_and_Household_Accounts.md
  src/customMetadata/GetStartedChecklistSection.CreateConstituentRecords_NPSP.md
  src/labels/CustomLabels.labels
  src/lwc/gsLabelMapper/gsLabelMapper.js
  src/package.xml
  src/staticresources/CumulusStaticResources.resource
Labels: Nonprofit-Optimize, Not-to-master

#6179 [W-8545411] Checklist Section 4
  StaticResourceSources/gsAssets/step/Find_Records_with_Global_Search.svg
  StaticResourceSources/gsAssets/step/Stay_on_Track_with_Activities.svg
  StaticResourceSources/gsAssets/step/Work_with_Multiple_Records_Using_List_Views.svg
  src/customMetadata/GetStartedChecklistItem.Global_Search.md
  src/customMetadata/GetStartedChecklistItem.Stay_Track_End_User.md
  src/customMetadata/GetStartedChecklistItem.Work_Multiple_Records.md
  src/customMetadata/GetStartedChecklistSection.Work_with_Records.md
  src/labels/CustomLabels.labels
  src/lwc/gsLabelMapper/gsLabelMapper.js
  src/package.xml
  src/staticresources/CumulusStaticResources.resource
Labels: Nonprofit-Optimize, Not-to-master

#6156 [GS End User][W-8545419] Checklist Section 5
  StaticResourceSources/gsAssets/step/Create_a_Report_from_a_Standard_Report_Type.svg
  StaticResourceSources/gsAssets/step/Run_a_Prebuilt_NPSP_Report.svg
  StaticResourceSources/gsAssets/step/View_a_Dashboard.svg
  src/customMetadata/GetStartedChecklistItem.Prebuilt_NPSP_Report.md
  src/customMetadata/GetStartedChecklistItem.Standard_Repor_Type.md
  src/customMetadata/GetStartedChecklistItem.View_Dashboard.md
  src/customMetadata/GetStartedChecklistSection.Your_Data.md
  src/labels/CustomLabels.labels
  src/lwc/gsLabelMapper/gsLabelMapper.js
  src/package.xml
  src/staticresources/CumulusStaticResources.resource
Labels: Nonprofit-Optimize, Not-to-master

#6192 Gift Entry: Exclude ACH fields from Template Builder
  src/lwc/geTemplateBuilderFormFields/geTemplateBuilderFormFields.js
Labels: Not-to-master

#6195 RD2: Add ACH Last 4 Field to Recurring Donation
  src/objects/npe03__Recurring_Donation__c.object
  src/package.xml
  unpackaged/config/rd2_post_config/profiles/Admin.profile
  unpackaged/config/rd2_post_config/profiles/Standard.profile
Labels: QE - Test

#6131 [GS][W-8486439] Replace links
  src/customMetadata/GetStartedChecklistItem.Add_User.md
  src/customMetadata/GetStartedChecklistItem.Communicate_With_Users.md
  src/customMetadata/GetStartedChecklistItem.Create_a_Donation.md
  src/customMetadata/GetStartedChecklistItem.Custom_Fields.md
  src/customMetadata/GetStartedChecklistItem.Fundraising_process.md
  src/customMetadata/GetStartedChecklistItem.Go_Further.md
  src/customMetadata/GetStartedChecklistItem.Import_Data.md
  src/customMetadata/GetStartedChecklistItem.Manage_Change.md
  src/customMetadata/GetStartedChecklistItem.NPSP_Cloud.md
  src/customMetadata/GetStartedChecklistItem.NPSP_Guide.md
  src/customMetadata/GetStartedChecklistItem.Page_Layouts.md
  src/customMetadata/GetStartedChecklistItem.Prepare_NPSP_Cloud.md
  src/customMetadata/GetStartedChecklistItem.Review_Company.md
  src/customMetadata/GetStartedChecklistItem.Running_Reports.md
  src/customMetadata/GetStartedChecklistItem.Setup_Contact.md
  src/customMetadata/GetStartedChecklistItem.Stay_Track.md
  src/customMetadata/GetStartedChecklistItem.Train_Users.md
  src/lwc/gsApplicationStatus/gsApplicationStatus.html
  src/lwc/gsVideoHeader/gsVideoHeader.html
Labels: Nonprofit-Optimize
