Repository SalesforceFoundation/NPSP, pull requests merged in 2022-04, with the labels that each got.

#6884 RD2 - Implement SaveRecurringDonation method
  force-app/main/default/classes/InputFieldView.cls
  force-app/main/default/classes/InputFieldView.cls-meta.xml
  force-app/main/default/classes/RD2_AppView.cls
  force-app/main/default/classes/RD2_AppView.cls-meta.xml
  force-app/main/default/classes/RD2_EntryFormController.cls
  force-app/main/default/classes/RD2_EntryFormController_TEST.cls
  force-app/main/default/classes/RD2_PauseForm_TEST.cls
  force-app/main/default/classes/RD2_RecordView.cls
  force-app/main/default/classes/RD2_RecordView.cls-meta.xml
  force-app/main/default/classes/RD2_SaveRequest.cls
  force-app/main/default/classes/RD2_SaveRequest.cls-meta.xml
  force-app/main/default/classes/RD2_ValidationService.cls
  force-app/main/default/classes/RD2_ValidationService_TEST.cls
  force-app/main/default/classes/SaveErrorView.cls
  force-app/main/default/classes/SaveErrorView.cls-meta.xml
  force-app/main/default/classes/SaveResultView.cls
  force-app/main/default/classes/SaveResultView.cls-meta.xml
  force-app/main/default/classes/UTIL_Permissions.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/geFormWidgetTokenizeCard/__tests__/geFormWidgetTokenizeCard.test.js
  force-app/main/default/lwc/rd2ElevateCreditCardForm/rd2ElevateCreditCardForm.js
  force-app/main/default/lwc/rd2EntryForm/__tests__/rd2EntryForm.test.js
  force-app/main/default/lwc/rd2EntryForm/__tests__/rd2EntryFormTestHelpers.js
  force-app/main/default/lwc/rd2EntryForm/rd2EntryForm.html
  force-app/main/default/lwc/rd2EntryForm/rd2EntryForm.js
  force-app/main/default/lwc/rd2Service/__tests__/rd2Service.test.js
  force-app/main/default/lwc/rd2Service/actions.js
  force-app/main/default/lwc/rd2Service/model.js
  force-app/main/default/lwc/rd2Service/rd2Service.js
  force-app/main/default/lwc/util/util.js
  force-app/main/default/lwc/utilCommon/__tests__/utilCommon.test.js
  force-app/main/default/lwc/utilCommon/utilCommon.js
  force-app/main/default/lwc/utilPageLevelMessage/utilPageLevelMessage.js
  jest.config.js
  tests/__mocks__/apex/data/getInitialView.json
  tests/__mocks__/lightning/uiRecordApi.js
Labels: Instrumentation

#6906 [Gift Entry] Extend Callout TImeout
  force-app/main/default/classes/ElevateBatchService.cls
  force-app/main/default/classes/GE_PaymentServices.cls
Labels: bug, Instrumentation

#6922 [DO NOT MERGE] - Investigating Elevate Functionality in Communities
  force-app/main/default/lwc/testBuildLightningOrigin/testBuildLightningOrigin.html
  force-app/main/default/lwc/testBuildLightningOrigin/testBuildLightningOrigin.js
  force-app/main/default/lwc/testBuildLightningOrigin/testBuildLightningOrigin.js-meta.xml
  force-app/main/default/pages/GE_TokenizeCard.page
  force-app/main/default/permissionsets/Recurring_Donations.permissionset-meta.xml
Labels: Do Not Merge
